// Code generated by MockGen. DO NOT EDIT.
// Source: app.go
//
// Generated by this command:
//
//	mockgen -package=main_test -source=app.go -destination=mock.app_test.go
//

// Package main_test is a generated GoMock package.
package main_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// EnsureBPFFS mocks base method.
func (m *MockApp) EnsureBPFFS() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureBPFFS")
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureBPFFS indicates an expected call of EnsureBPFFS.
func (mr *MockAppMockRecorder) EnsureBPFFS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureBPFFS", reflect.TypeOf((*MockApp)(nil).EnsureBPFFS))
}

// Load mocks base method.
func (m *MockApp) Load() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockAppMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockApp)(nil).Load))
}

// RootCheck mocks base method.
func (m *MockApp) RootCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// RootCheck indicates an expected call of RootCheck.
func (mr *MockAppMockRecorder) RootCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootCheck", reflect.TypeOf((*MockApp)(nil).RootCheck))
}

// RunCmd mocks base method.
func (m *MockApp) RunCmd(args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RunCmd", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunCmd indicates an expected call of RunCmd.
func (mr *MockAppMockRecorder) RunCmd(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCmd", reflect.TypeOf((*MockApp)(nil).RunCmd), args...)
}

// SetMark mocks base method.
func (m *MockApp) SetMark(mark uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMark", mark)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMark indicates an expected call of SetMark.
func (mr *MockAppMockRecorder) SetMark(mark any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMark", reflect.TypeOf((*MockApp)(nil).SetMark), mark)
}

// Unload mocks base method.
func (m *MockApp) Unload() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unload")
	ret0, _ := ret[0].(error)
	return ret0
}

// Unload indicates an expected call of Unload.
func (mr *MockAppMockRecorder) Unload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unload", reflect.TypeOf((*MockApp)(nil).Unload))
}

// UnloadBPF mocks base method.
func (m *MockApp) UnloadBPF() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnloadBPF")
	ret0, _ := ret[0].(error)
	return ret0
}

// UnloadBPF indicates an expected call of UnloadBPF.
func (mr *MockAppMockRecorder) UnloadBPF() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnloadBPF", reflect.TypeOf((*MockApp)(nil).UnloadBPF))
}

// WriteTempBPFObj mocks base method.
func (m *MockApp) WriteTempBPFObj() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteTempBPFObj")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteTempBPFObj indicates an expected call of WriteTempBPFObj.
func (mr *MockAppMockRecorder) WriteTempBPFObj() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteTempBPFObj", reflect.TypeOf((*MockApp)(nil).WriteTempBPFObj))
}
