// Code generated by MockGen. DO NOT EDIT.
// Source: world.go
//
// Generated by this command:
//
//	mockgen -package=main_test -source=world.go -destination=mock.world_test.go
//

// Package main_test is a generated GoMock package.
package main_test

import (
	os "os"
	reflect "reflect"

	main "github.com/powerman/ebpf-same-cgroup-mark"
	gomock "go.uber.org/mock/gomock"
)

// MockWorld is a mock of World interface.
type MockWorld struct {
	ctrl     *gomock.Controller
	recorder *MockWorldMockRecorder
	isgomock struct{}
}

// MockWorldMockRecorder is the mock recorder for MockWorld.
type MockWorldMockRecorder struct {
	mock *MockWorld
}

// NewMockWorld creates a new mock instance.
func NewMockWorld(ctrl *gomock.Controller) *MockWorld {
	mock := &MockWorld{ctrl: ctrl}
	mock.recorder = &MockWorldMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorld) EXPECT() *MockWorldMockRecorder {
	return m.recorder
}

// ExecCommand mocks base method.
func (m *MockWorld) ExecCommand(name string, args ...string) main.WorldExecCmd {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecCommand", varargs...)
	ret0, _ := ret[0].(main.WorldExecCmd)
	return ret0
}

// ExecCommand indicates an expected call of ExecCommand.
func (mr *MockWorldMockRecorder) ExecCommand(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecCommand", reflect.TypeOf((*MockWorld)(nil).ExecCommand), varargs...)
}

// OsCreateTemp mocks base method.
func (m *MockWorld) OsCreateTemp(dir, pattern string) (main.WorldOsFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsCreateTemp", dir, pattern)
	ret0, _ := ret[0].(main.WorldOsFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OsCreateTemp indicates an expected call of OsCreateTemp.
func (mr *MockWorldMockRecorder) OsCreateTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsCreateTemp", reflect.TypeOf((*MockWorld)(nil).OsCreateTemp), dir, pattern)
}

// OsGeteuid mocks base method.
func (m *MockWorld) OsGeteuid() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsGeteuid")
	ret0, _ := ret[0].(int)
	return ret0
}

// OsGeteuid indicates an expected call of OsGeteuid.
func (mr *MockWorldMockRecorder) OsGeteuid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsGeteuid", reflect.TypeOf((*MockWorld)(nil).OsGeteuid))
}

// OsMkdirAll mocks base method.
func (m *MockWorld) OsMkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsMkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// OsMkdirAll indicates an expected call of OsMkdirAll.
func (mr *MockWorldMockRecorder) OsMkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsMkdirAll", reflect.TypeOf((*MockWorld)(nil).OsMkdirAll), path, perm)
}

// OsRemove mocks base method.
func (m *MockWorld) OsRemove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsRemove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// OsRemove indicates an expected call of OsRemove.
func (mr *MockWorldMockRecorder) OsRemove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsRemove", reflect.TypeOf((*MockWorld)(nil).OsRemove), name)
}

// OsRemoveAll mocks base method.
func (m *MockWorld) OsRemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsRemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// OsRemoveAll indicates an expected call of OsRemoveAll.
func (mr *MockWorldMockRecorder) OsRemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsRemoveAll", reflect.TypeOf((*MockWorld)(nil).OsRemoveAll), path)
}

// OsStat mocks base method.
func (m *MockWorld) OsStat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsStat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OsStat indicates an expected call of OsStat.
func (mr *MockWorldMockRecorder) OsStat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsStat", reflect.TypeOf((*MockWorld)(nil).OsStat), name)
}

// MockWorldExecCmd is a mock of WorldExecCmd interface.
type MockWorldExecCmd struct {
	ctrl     *gomock.Controller
	recorder *MockWorldExecCmdMockRecorder
	isgomock struct{}
}

// MockWorldExecCmdMockRecorder is the mock recorder for MockWorldExecCmd.
type MockWorldExecCmdMockRecorder struct {
	mock *MockWorldExecCmd
}

// NewMockWorldExecCmd creates a new mock instance.
func NewMockWorldExecCmd(ctrl *gomock.Controller) *MockWorldExecCmd {
	mock := &MockWorldExecCmd{ctrl: ctrl}
	mock.recorder = &MockWorldExecCmdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldExecCmd) EXPECT() *MockWorldExecCmdMockRecorder {
	return m.recorder
}

// CombinedOutput mocks base method.
func (m *MockWorldExecCmd) CombinedOutput() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CombinedOutput")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CombinedOutput indicates an expected call of CombinedOutput.
func (mr *MockWorldExecCmdMockRecorder) CombinedOutput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CombinedOutput", reflect.TypeOf((*MockWorldExecCmd)(nil).CombinedOutput))
}

// Run mocks base method.
func (m *MockWorldExecCmd) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockWorldExecCmdMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWorldExecCmd)(nil).Run))
}

// MockWorldOsFile is a mock of WorldOsFile interface.
type MockWorldOsFile struct {
	ctrl     *gomock.Controller
	recorder *MockWorldOsFileMockRecorder
	isgomock struct{}
}

// MockWorldOsFileMockRecorder is the mock recorder for MockWorldOsFile.
type MockWorldOsFileMockRecorder struct {
	mock *MockWorldOsFile
}

// NewMockWorldOsFile creates a new mock instance.
func NewMockWorldOsFile(ctrl *gomock.Controller) *MockWorldOsFile {
	mock := &MockWorldOsFile{ctrl: ctrl}
	mock.recorder = &MockWorldOsFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldOsFile) EXPECT() *MockWorldOsFileMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWorldOsFile) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWorldOsFileMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorldOsFile)(nil).Close))
}

// Name mocks base method.
func (m *MockWorldOsFile) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockWorldOsFileMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockWorldOsFile)(nil).Name))
}

// Write mocks base method.
func (m *MockWorldOsFile) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockWorldOsFileMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWorldOsFile)(nil).Write), p)
}
