// Code generated by MockGen. DO NOT EDIT.
// Source: world.go
//
// Generated by this command:
//
//	mockgen -package=main_test -source=world.go -destination=mock.world_test.go
//

// Package main_test is a generated GoMock package.
package main_test

import (
	context "context"
	os "os"
	reflect "reflect"

	main "github.com/powerman/ebpf-same-cgroup-mark"
	gomock "go.uber.org/mock/gomock"
)

// MockWorld is a mock of World interface.
type MockWorld struct {
	ctrl     *gomock.Controller
	recorder *MockWorldMockRecorder
	isgomock struct{}
}

// MockWorldMockRecorder is the mock recorder for MockWorld.
type MockWorldMockRecorder struct {
	mock *MockWorld
}

// NewMockWorld creates a new mock instance.
func NewMockWorld(ctrl *gomock.Controller) *MockWorld {
	mock := &MockWorld{ctrl: ctrl}
	mock.recorder = &MockWorldMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorld) EXPECT() *MockWorldMockRecorder {
	return m.recorder
}

// CmdOutput mocks base method.
func (m *MockWorld) CmdOutput(name string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CmdOutput", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CmdOutput indicates an expected call of CmdOutput.
func (mr *MockWorldMockRecorder) CmdOutput(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdOutput", reflect.TypeOf((*MockWorld)(nil).CmdOutput), varargs...)
}

// CmdRun mocks base method.
func (m *MockWorld) CmdRun(ctx context.Context, name string, args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CmdRun", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CmdRun indicates an expected call of CmdRun.
func (mr *MockWorldMockRecorder) CmdRun(ctx, name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CmdRun", reflect.TypeOf((*MockWorld)(nil).CmdRun), varargs...)
}

// OsCreateTemp mocks base method.
func (m *MockWorld) OsCreateTemp(dir, pattern string) (main.TempFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsCreateTemp", dir, pattern)
	ret0, _ := ret[0].(main.TempFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OsCreateTemp indicates an expected call of OsCreateTemp.
func (mr *MockWorldMockRecorder) OsCreateTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsCreateTemp", reflect.TypeOf((*MockWorld)(nil).OsCreateTemp), dir, pattern)
}

// OsGeteuid mocks base method.
func (m *MockWorld) OsGeteuid() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsGeteuid")
	ret0, _ := ret[0].(int)
	return ret0
}

// OsGeteuid indicates an expected call of OsGeteuid.
func (mr *MockWorldMockRecorder) OsGeteuid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsGeteuid", reflect.TypeOf((*MockWorld)(nil).OsGeteuid))
}

// OsMkdirAll mocks base method.
func (m *MockWorld) OsMkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsMkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// OsMkdirAll indicates an expected call of OsMkdirAll.
func (mr *MockWorldMockRecorder) OsMkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsMkdirAll", reflect.TypeOf((*MockWorld)(nil).OsMkdirAll), path, perm)
}

// OsRemoveAll mocks base method.
func (m *MockWorld) OsRemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsRemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// OsRemoveAll indicates an expected call of OsRemoveAll.
func (mr *MockWorldMockRecorder) OsRemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsRemoveAll", reflect.TypeOf((*MockWorld)(nil).OsRemoveAll), path)
}

// OsStat mocks base method.
func (m *MockWorld) OsStat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsStat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OsStat indicates an expected call of OsStat.
func (mr *MockWorldMockRecorder) OsStat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsStat", reflect.TypeOf((*MockWorld)(nil).OsStat), name)
}

// MockTempFile is a mock of TempFile interface.
type MockTempFile struct {
	ctrl     *gomock.Controller
	recorder *MockTempFileMockRecorder
	isgomock struct{}
}

// MockTempFileMockRecorder is the mock recorder for MockTempFile.
type MockTempFileMockRecorder struct {
	mock *MockTempFile
}

// NewMockTempFile creates a new mock instance.
func NewMockTempFile(ctrl *gomock.Controller) *MockTempFile {
	mock := &MockTempFile{ctrl: ctrl}
	mock.recorder = &MockTempFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTempFile) EXPECT() *MockTempFileMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTempFile) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTempFileMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTempFile)(nil).Close))
}

// Name mocks base method.
func (m *MockTempFile) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTempFileMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTempFile)(nil).Name))
}

// Write mocks base method.
func (m *MockTempFile) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockTempFileMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockTempFile)(nil).Write), p)
}
