// Code generated by go-mockgen 2.1.1; DO NOT EDIT.

package app

import (
	"io/fs"
	"sync"

	app "github.com/powerman/ebpf-same-cgroup-mark/internal/app"
)

// MockStubWorld is a mock implementation of the World interface (from the
// package github.com/powerman/ebpf-same-cgroup-mark/internal/app) used for
// unit testing.
type MockStubWorld struct {
	// BpftoolCgroupAttachFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupAttach.
	BpftoolCgroupAttachFunc *StubWorldBpftoolCgroupAttachFunc
	// BpftoolCgroupDetachFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupDetach.
	BpftoolCgroupDetachFunc *StubWorldBpftoolCgroupDetachFunc
	// BpftoolCgroupShowFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupShow.
	BpftoolCgroupShowFunc *StubWorldBpftoolCgroupShowFunc
	// BpftoolMapUpdateFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolMapUpdate.
	BpftoolMapUpdateFunc *StubWorldBpftoolMapUpdateFunc
	// BpftoolProgLoadAllFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolProgLoadAll.
	BpftoolProgLoadAllFunc *StubWorldBpftoolProgLoadAllFunc
	// MountBPFFunc is an instance of a mock function object controlling the
	// behavior of the method MountBPF.
	MountBPFFunc *StubWorldMountBPFFunc
	// MountpointFunc is an instance of a mock function object controlling
	// the behavior of the method Mountpoint.
	MountpointFunc *StubWorldMountpointFunc
	// OsCreateTempFunc is an instance of a mock function object controlling
	// the behavior of the method OsCreateTemp.
	OsCreateTempFunc *StubWorldOsCreateTempFunc
	// OsGeteuidFunc is an instance of a mock function object controlling
	// the behavior of the method OsGeteuid.
	OsGeteuidFunc *StubWorldOsGeteuidFunc
	// OsMkdirAllFunc is an instance of a mock function object controlling
	// the behavior of the method OsMkdirAll.
	OsMkdirAllFunc *StubWorldOsMkdirAllFunc
	// OsRemoveFunc is an instance of a mock function object controlling the
	// behavior of the method OsRemove.
	OsRemoveFunc *StubWorldOsRemoveFunc
	// OsRemoveAllFunc is an instance of a mock function object controlling
	// the behavior of the method OsRemoveAll.
	OsRemoveAllFunc *StubWorldOsRemoveAllFunc
	// OsStatFunc is an instance of a mock function object controlling the
	// behavior of the method OsStat.
	OsStatFunc *StubWorldOsStatFunc
}

// NewMockStubWorld creates a new mock of the World interface. All methods
// return zero values for all results, unless overwritten.
func NewMockStubWorld() *MockStubWorld {
	return &MockStubWorld{
		BpftoolCgroupAttachFunc: &StubWorldBpftoolCgroupAttachFunc{
			defaultHook: func(string, string, string) (r0 error) {
				return
			},
		},
		BpftoolCgroupDetachFunc: &StubWorldBpftoolCgroupDetachFunc{
			defaultHook: func(string, string, string) (r0 error) {
				return
			},
		},
		BpftoolCgroupShowFunc: &StubWorldBpftoolCgroupShowFunc{
			defaultHook: func(string) (r0 []byte, r1 error) {
				return
			},
		},
		BpftoolMapUpdateFunc: &StubWorldBpftoolMapUpdateFunc{
			defaultHook: func(...string) (r0 error) {
				return
			},
		},
		BpftoolProgLoadAllFunc: &StubWorldBpftoolProgLoadAllFunc{
			defaultHook: func(string, string, string) (r0 []byte, r1 error) {
				return
			},
		},
		MountBPFFunc: &StubWorldMountBPFFunc{
			defaultHook: func(string, string) (r0 []byte, r1 error) {
				return
			},
		},
		MountpointFunc: &StubWorldMountpointFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
		OsCreateTempFunc: &StubWorldOsCreateTempFunc{
			defaultHook: func(string, string) (r0 app.WorldOsFile, r1 error) {
				return
			},
		},
		OsGeteuidFunc: &StubWorldOsGeteuidFunc{
			defaultHook: func() (r0 int) {
				return
			},
		},
		OsMkdirAllFunc: &StubWorldOsMkdirAllFunc{
			defaultHook: func(string, fs.FileMode) (r0 error) {
				return
			},
		},
		OsRemoveFunc: &StubWorldOsRemoveFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
		OsRemoveAllFunc: &StubWorldOsRemoveAllFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
		OsStatFunc: &StubWorldOsStatFunc{
			defaultHook: func(string) (r0 fs.FileInfo, r1 error) {
				return
			},
		},
	}
}

// NewStrictMockStubWorld creates a new mock of the World interface. All
// methods panic on invocation, unless overwritten.
func NewStrictMockStubWorld() *MockStubWorld {
	return &MockStubWorld{
		BpftoolCgroupAttachFunc: &StubWorldBpftoolCgroupAttachFunc{
			defaultHook: func(string, string, string) error {
				panic("unexpected invocation of MockStubWorld.BpftoolCgroupAttach")
			},
		},
		BpftoolCgroupDetachFunc: &StubWorldBpftoolCgroupDetachFunc{
			defaultHook: func(string, string, string) error {
				panic("unexpected invocation of MockStubWorld.BpftoolCgroupDetach")
			},
		},
		BpftoolCgroupShowFunc: &StubWorldBpftoolCgroupShowFunc{
			defaultHook: func(string) ([]byte, error) {
				panic("unexpected invocation of MockStubWorld.BpftoolCgroupShow")
			},
		},
		BpftoolMapUpdateFunc: &StubWorldBpftoolMapUpdateFunc{
			defaultHook: func(...string) error {
				panic("unexpected invocation of MockStubWorld.BpftoolMapUpdate")
			},
		},
		BpftoolProgLoadAllFunc: &StubWorldBpftoolProgLoadAllFunc{
			defaultHook: func(string, string, string) ([]byte, error) {
				panic("unexpected invocation of MockStubWorld.BpftoolProgLoadAll")
			},
		},
		MountBPFFunc: &StubWorldMountBPFFunc{
			defaultHook: func(string, string) ([]byte, error) {
				panic("unexpected invocation of MockStubWorld.MountBPF")
			},
		},
		MountpointFunc: &StubWorldMountpointFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockStubWorld.Mountpoint")
			},
		},
		OsCreateTempFunc: &StubWorldOsCreateTempFunc{
			defaultHook: func(string, string) (app.WorldOsFile, error) {
				panic("unexpected invocation of MockStubWorld.OsCreateTemp")
			},
		},
		OsGeteuidFunc: &StubWorldOsGeteuidFunc{
			defaultHook: func() int {
				panic("unexpected invocation of MockStubWorld.OsGeteuid")
			},
		},
		OsMkdirAllFunc: &StubWorldOsMkdirAllFunc{
			defaultHook: func(string, fs.FileMode) error {
				panic("unexpected invocation of MockStubWorld.OsMkdirAll")
			},
		},
		OsRemoveFunc: &StubWorldOsRemoveFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockStubWorld.OsRemove")
			},
		},
		OsRemoveAllFunc: &StubWorldOsRemoveAllFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockStubWorld.OsRemoveAll")
			},
		},
		OsStatFunc: &StubWorldOsStatFunc{
			defaultHook: func(string) (fs.FileInfo, error) {
				panic("unexpected invocation of MockStubWorld.OsStat")
			},
		},
	}
}

// NewMockStubWorldFrom creates a new mock of the MockStubWorld interface.
// All methods delegate to the given implementation, unless overwritten.
func NewMockStubWorldFrom(i app.World) *MockStubWorld {
	return &MockStubWorld{
		BpftoolCgroupAttachFunc: &StubWorldBpftoolCgroupAttachFunc{
			defaultHook: i.BpftoolCgroupAttach,
		},
		BpftoolCgroupDetachFunc: &StubWorldBpftoolCgroupDetachFunc{
			defaultHook: i.BpftoolCgroupDetach,
		},
		BpftoolCgroupShowFunc: &StubWorldBpftoolCgroupShowFunc{
			defaultHook: i.BpftoolCgroupShow,
		},
		BpftoolMapUpdateFunc: &StubWorldBpftoolMapUpdateFunc{
			defaultHook: i.BpftoolMapUpdate,
		},
		BpftoolProgLoadAllFunc: &StubWorldBpftoolProgLoadAllFunc{
			defaultHook: i.BpftoolProgLoadAll,
		},
		MountBPFFunc: &StubWorldMountBPFFunc{
			defaultHook: i.MountBPF,
		},
		MountpointFunc: &StubWorldMountpointFunc{
			defaultHook: i.Mountpoint,
		},
		OsCreateTempFunc: &StubWorldOsCreateTempFunc{
			defaultHook: i.OsCreateTemp,
		},
		OsGeteuidFunc: &StubWorldOsGeteuidFunc{
			defaultHook: i.OsGeteuid,
		},
		OsMkdirAllFunc: &StubWorldOsMkdirAllFunc{
			defaultHook: i.OsMkdirAll,
		},
		OsRemoveFunc: &StubWorldOsRemoveFunc{
			defaultHook: i.OsRemove,
		},
		OsRemoveAllFunc: &StubWorldOsRemoveAllFunc{
			defaultHook: i.OsRemoveAll,
		},
		OsStatFunc: &StubWorldOsStatFunc{
			defaultHook: i.OsStat,
		},
	}
}

// StubWorldBpftoolCgroupAttachFunc describes the behavior when the
// BpftoolCgroupAttach method of the parent MockStubWorld instance is
// invoked.
type StubWorldBpftoolCgroupAttachFunc struct {
	defaultHook func(string, string, string) error
	hooks       []func(string, string, string) error
	history     []StubWorldBpftoolCgroupAttachFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupAttach delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorld) BpftoolCgroupAttach(v0 string, v1 string, v2 string) error {
	r0 := m.BpftoolCgroupAttachFunc.nextHook()(v0, v1, v2)
	m.BpftoolCgroupAttachFunc.appendCall(StubWorldBpftoolCgroupAttachFuncCall{v0, v1, v2, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolCgroupAttach
// method of the parent MockStubWorld instance is invoked and the hook queue
// is empty.
func (f *StubWorldBpftoolCgroupAttachFunc) SetDefaultHook(hook func(string, string, string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupAttach method of the parent MockStubWorld instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *StubWorldBpftoolCgroupAttachFunc) PushHook(hook func(string, string, string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldBpftoolCgroupAttachFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, string, string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldBpftoolCgroupAttachFunc) PushReturn(r0 error) {
	f.PushHook(func(string, string, string) error {
		return r0
	})
}

func (f *StubWorldBpftoolCgroupAttachFunc) nextHook() func(string, string, string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldBpftoolCgroupAttachFunc) appendCall(r0 StubWorldBpftoolCgroupAttachFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldBpftoolCgroupAttachFuncCall
// objects describing the invocations of this function.
func (f *StubWorldBpftoolCgroupAttachFunc) History() []StubWorldBpftoolCgroupAttachFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldBpftoolCgroupAttachFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldBpftoolCgroupAttachFuncCall is an object that describes an
// invocation of method BpftoolCgroupAttach on an instance of MockStubWorld.
type StubWorldBpftoolCgroupAttachFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldBpftoolCgroupAttachFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldBpftoolCgroupAttachFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldBpftoolCgroupDetachFunc describes the behavior when the
// BpftoolCgroupDetach method of the parent MockStubWorld instance is
// invoked.
type StubWorldBpftoolCgroupDetachFunc struct {
	defaultHook func(string, string, string) error
	hooks       []func(string, string, string) error
	history     []StubWorldBpftoolCgroupDetachFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupDetach delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorld) BpftoolCgroupDetach(v0 string, v1 string, v2 string) error {
	r0 := m.BpftoolCgroupDetachFunc.nextHook()(v0, v1, v2)
	m.BpftoolCgroupDetachFunc.appendCall(StubWorldBpftoolCgroupDetachFuncCall{v0, v1, v2, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolCgroupDetach
// method of the parent MockStubWorld instance is invoked and the hook queue
// is empty.
func (f *StubWorldBpftoolCgroupDetachFunc) SetDefaultHook(hook func(string, string, string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupDetach method of the parent MockStubWorld instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *StubWorldBpftoolCgroupDetachFunc) PushHook(hook func(string, string, string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldBpftoolCgroupDetachFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, string, string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldBpftoolCgroupDetachFunc) PushReturn(r0 error) {
	f.PushHook(func(string, string, string) error {
		return r0
	})
}

func (f *StubWorldBpftoolCgroupDetachFunc) nextHook() func(string, string, string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldBpftoolCgroupDetachFunc) appendCall(r0 StubWorldBpftoolCgroupDetachFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldBpftoolCgroupDetachFuncCall
// objects describing the invocations of this function.
func (f *StubWorldBpftoolCgroupDetachFunc) History() []StubWorldBpftoolCgroupDetachFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldBpftoolCgroupDetachFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldBpftoolCgroupDetachFuncCall is an object that describes an
// invocation of method BpftoolCgroupDetach on an instance of MockStubWorld.
type StubWorldBpftoolCgroupDetachFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldBpftoolCgroupDetachFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldBpftoolCgroupDetachFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldBpftoolCgroupShowFunc describes the behavior when the
// BpftoolCgroupShow method of the parent MockStubWorld instance is invoked.
type StubWorldBpftoolCgroupShowFunc struct {
	defaultHook func(string) ([]byte, error)
	hooks       []func(string) ([]byte, error)
	history     []StubWorldBpftoolCgroupShowFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupShow delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorld) BpftoolCgroupShow(v0 string) ([]byte, error) {
	r0, r1 := m.BpftoolCgroupShowFunc.nextHook()(v0)
	m.BpftoolCgroupShowFunc.appendCall(StubWorldBpftoolCgroupShowFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the BpftoolCgroupShow
// method of the parent MockStubWorld instance is invoked and the hook queue
// is empty.
func (f *StubWorldBpftoolCgroupShowFunc) SetDefaultHook(hook func(string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupShow method of the parent MockStubWorld instance invokes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *StubWorldBpftoolCgroupShowFunc) PushHook(hook func(string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldBpftoolCgroupShowFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldBpftoolCgroupShowFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string) ([]byte, error) {
		return r0, r1
	})
}

func (f *StubWorldBpftoolCgroupShowFunc) nextHook() func(string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldBpftoolCgroupShowFunc) appendCall(r0 StubWorldBpftoolCgroupShowFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldBpftoolCgroupShowFuncCall objects
// describing the invocations of this function.
func (f *StubWorldBpftoolCgroupShowFunc) History() []StubWorldBpftoolCgroupShowFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldBpftoolCgroupShowFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldBpftoolCgroupShowFuncCall is an object that describes an
// invocation of method BpftoolCgroupShow on an instance of MockStubWorld.
type StubWorldBpftoolCgroupShowFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldBpftoolCgroupShowFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldBpftoolCgroupShowFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldBpftoolMapUpdateFunc describes the behavior when the
// BpftoolMapUpdate method of the parent MockStubWorld instance is invoked.
type StubWorldBpftoolMapUpdateFunc struct {
	defaultHook func(...string) error
	hooks       []func(...string) error
	history     []StubWorldBpftoolMapUpdateFuncCall
	mutex       sync.Mutex
}

// BpftoolMapUpdate delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorld) BpftoolMapUpdate(v0 ...string) error {
	r0 := m.BpftoolMapUpdateFunc.nextHook()(v0...)
	m.BpftoolMapUpdateFunc.appendCall(StubWorldBpftoolMapUpdateFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolMapUpdate
// method of the parent MockStubWorld instance is invoked and the hook queue
// is empty.
func (f *StubWorldBpftoolMapUpdateFunc) SetDefaultHook(hook func(...string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolMapUpdate method of the parent MockStubWorld instance invokes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *StubWorldBpftoolMapUpdateFunc) PushHook(hook func(...string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldBpftoolMapUpdateFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(...string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldBpftoolMapUpdateFunc) PushReturn(r0 error) {
	f.PushHook(func(...string) error {
		return r0
	})
}

func (f *StubWorldBpftoolMapUpdateFunc) nextHook() func(...string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldBpftoolMapUpdateFunc) appendCall(r0 StubWorldBpftoolMapUpdateFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldBpftoolMapUpdateFuncCall objects
// describing the invocations of this function.
func (f *StubWorldBpftoolMapUpdateFunc) History() []StubWorldBpftoolMapUpdateFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldBpftoolMapUpdateFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldBpftoolMapUpdateFuncCall is an object that describes an
// invocation of method BpftoolMapUpdate on an instance of MockStubWorld.
type StubWorldBpftoolMapUpdateFuncCall struct {
	// Arg0 is a slice containing the values of the variadic arguments
	// passed to this method invocation.
	Arg0 []string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation. The variadic slice argument is flattened in this array such
// that one positional argument and three variadic arguments would result in
// a slice of four, not two.
func (c StubWorldBpftoolMapUpdateFuncCall) Args() []interface{} {
	trailing := []interface{}{}
	for _, val := range c.Arg0 {
		trailing = append(trailing, val)
	}

	return append([]interface{}{}, trailing...)
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldBpftoolMapUpdateFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldBpftoolProgLoadAllFunc describes the behavior when the
// BpftoolProgLoadAll method of the parent MockStubWorld instance is
// invoked.
type StubWorldBpftoolProgLoadAllFunc struct {
	defaultHook func(string, string, string) ([]byte, error)
	hooks       []func(string, string, string) ([]byte, error)
	history     []StubWorldBpftoolProgLoadAllFuncCall
	mutex       sync.Mutex
}

// BpftoolProgLoadAll delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorld) BpftoolProgLoadAll(v0 string, v1 string, v2 string) ([]byte, error) {
	r0, r1 := m.BpftoolProgLoadAllFunc.nextHook()(v0, v1, v2)
	m.BpftoolProgLoadAllFunc.appendCall(StubWorldBpftoolProgLoadAllFuncCall{v0, v1, v2, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the BpftoolProgLoadAll
// method of the parent MockStubWorld instance is invoked and the hook queue
// is empty.
func (f *StubWorldBpftoolProgLoadAllFunc) SetDefaultHook(hook func(string, string, string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolProgLoadAll method of the parent MockStubWorld instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *StubWorldBpftoolProgLoadAllFunc) PushHook(hook func(string, string, string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldBpftoolProgLoadAllFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string, string, string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldBpftoolProgLoadAllFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string, string, string) ([]byte, error) {
		return r0, r1
	})
}

func (f *StubWorldBpftoolProgLoadAllFunc) nextHook() func(string, string, string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldBpftoolProgLoadAllFunc) appendCall(r0 StubWorldBpftoolProgLoadAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldBpftoolProgLoadAllFuncCall objects
// describing the invocations of this function.
func (f *StubWorldBpftoolProgLoadAllFunc) History() []StubWorldBpftoolProgLoadAllFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldBpftoolProgLoadAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldBpftoolProgLoadAllFuncCall is an object that describes an
// invocation of method BpftoolProgLoadAll on an instance of MockStubWorld.
type StubWorldBpftoolProgLoadAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldBpftoolProgLoadAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldBpftoolProgLoadAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldMountBPFFunc describes the behavior when the MountBPF method of
// the parent MockStubWorld instance is invoked.
type StubWorldMountBPFFunc struct {
	defaultHook func(string, string) ([]byte, error)
	hooks       []func(string, string) ([]byte, error)
	history     []StubWorldMountBPFFuncCall
	mutex       sync.Mutex
}

// MountBPF delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorld) MountBPF(v0 string, v1 string) ([]byte, error) {
	r0, r1 := m.MountBPFFunc.nextHook()(v0, v1)
	m.MountBPFFunc.appendCall(StubWorldMountBPFFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the MountBPF method of
// the parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldMountBPFFunc) SetDefaultHook(hook func(string, string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// MountBPF method of the parent MockStubWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldMountBPFFunc) PushHook(hook func(string, string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldMountBPFFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string, string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldMountBPFFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string, string) ([]byte, error) {
		return r0, r1
	})
}

func (f *StubWorldMountBPFFunc) nextHook() func(string, string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldMountBPFFunc) appendCall(r0 StubWorldMountBPFFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldMountBPFFuncCall objects
// describing the invocations of this function.
func (f *StubWorldMountBPFFunc) History() []StubWorldMountBPFFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldMountBPFFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldMountBPFFuncCall is an object that describes an invocation of
// method MountBPF on an instance of MockStubWorld.
type StubWorldMountBPFFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldMountBPFFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldMountBPFFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldMountpointFunc describes the behavior when the Mountpoint method
// of the parent MockStubWorld instance is invoked.
type StubWorldMountpointFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []StubWorldMountpointFuncCall
	mutex       sync.Mutex
}

// Mountpoint delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorld) Mountpoint(v0 string) error {
	r0 := m.MountpointFunc.nextHook()(v0)
	m.MountpointFunc.appendCall(StubWorldMountpointFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the Mountpoint method of
// the parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldMountpointFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Mountpoint method of the parent MockStubWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldMountpointFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldMountpointFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldMountpointFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *StubWorldMountpointFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldMountpointFunc) appendCall(r0 StubWorldMountpointFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldMountpointFuncCall objects
// describing the invocations of this function.
func (f *StubWorldMountpointFunc) History() []StubWorldMountpointFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldMountpointFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldMountpointFuncCall is an object that describes an invocation of
// method Mountpoint on an instance of MockStubWorld.
type StubWorldMountpointFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldMountpointFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldMountpointFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsCreateTempFunc describes the behavior when the OsCreateTemp
// method of the parent MockStubWorld instance is invoked.
type StubWorldOsCreateTempFunc struct {
	defaultHook func(string, string) (app.WorldOsFile, error)
	hooks       []func(string, string) (app.WorldOsFile, error)
	history     []StubWorldOsCreateTempFuncCall
	mutex       sync.Mutex
}

// OsCreateTemp delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorld) OsCreateTemp(v0 string, v1 string) (app.WorldOsFile, error) {
	r0, r1 := m.OsCreateTempFunc.nextHook()(v0, v1)
	m.OsCreateTempFunc.appendCall(StubWorldOsCreateTempFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the OsCreateTemp method
// of the parent MockStubWorld instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsCreateTempFunc) SetDefaultHook(hook func(string, string) (app.WorldOsFile, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsCreateTemp method of the parent MockStubWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsCreateTempFunc) PushHook(hook func(string, string) (app.WorldOsFile, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsCreateTempFunc) SetDefaultReturn(r0 app.WorldOsFile, r1 error) {
	f.SetDefaultHook(func(string, string) (app.WorldOsFile, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsCreateTempFunc) PushReturn(r0 app.WorldOsFile, r1 error) {
	f.PushHook(func(string, string) (app.WorldOsFile, error) {
		return r0, r1
	})
}

func (f *StubWorldOsCreateTempFunc) nextHook() func(string, string) (app.WorldOsFile, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsCreateTempFunc) appendCall(r0 StubWorldOsCreateTempFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsCreateTempFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsCreateTempFunc) History() []StubWorldOsCreateTempFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsCreateTempFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsCreateTempFuncCall is an object that describes an invocation
// of method OsCreateTemp on an instance of MockStubWorld.
type StubWorldOsCreateTempFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 app.WorldOsFile
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsCreateTempFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsCreateTempFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldOsGeteuidFunc describes the behavior when the OsGeteuid method
// of the parent MockStubWorld instance is invoked.
type StubWorldOsGeteuidFunc struct {
	defaultHook func() int
	hooks       []func() int
	history     []StubWorldOsGeteuidFuncCall
	mutex       sync.Mutex
}

// OsGeteuid delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorld) OsGeteuid() int {
	r0 := m.OsGeteuidFunc.nextHook()()
	m.OsGeteuidFunc.appendCall(StubWorldOsGeteuidFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsGeteuid method of
// the parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldOsGeteuidFunc) SetDefaultHook(hook func() int) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsGeteuid method of the parent MockStubWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsGeteuidFunc) PushHook(hook func() int) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsGeteuidFunc) SetDefaultReturn(r0 int) {
	f.SetDefaultHook(func() int {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsGeteuidFunc) PushReturn(r0 int) {
	f.PushHook(func() int {
		return r0
	})
}

func (f *StubWorldOsGeteuidFunc) nextHook() func() int {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsGeteuidFunc) appendCall(r0 StubWorldOsGeteuidFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsGeteuidFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsGeteuidFunc) History() []StubWorldOsGeteuidFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsGeteuidFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsGeteuidFuncCall is an object that describes an invocation of
// method OsGeteuid on an instance of MockStubWorld.
type StubWorldOsGeteuidFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 int
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsGeteuidFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsGeteuidFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsMkdirAllFunc describes the behavior when the OsMkdirAll method
// of the parent MockStubWorld instance is invoked.
type StubWorldOsMkdirAllFunc struct {
	defaultHook func(string, fs.FileMode) error
	hooks       []func(string, fs.FileMode) error
	history     []StubWorldOsMkdirAllFuncCall
	mutex       sync.Mutex
}

// OsMkdirAll delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorld) OsMkdirAll(v0 string, v1 fs.FileMode) error {
	r0 := m.OsMkdirAllFunc.nextHook()(v0, v1)
	m.OsMkdirAllFunc.appendCall(StubWorldOsMkdirAllFuncCall{v0, v1, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsMkdirAll method of
// the parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldOsMkdirAllFunc) SetDefaultHook(hook func(string, fs.FileMode) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsMkdirAll method of the parent MockStubWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsMkdirAllFunc) PushHook(hook func(string, fs.FileMode) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsMkdirAllFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, fs.FileMode) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsMkdirAllFunc) PushReturn(r0 error) {
	f.PushHook(func(string, fs.FileMode) error {
		return r0
	})
}

func (f *StubWorldOsMkdirAllFunc) nextHook() func(string, fs.FileMode) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsMkdirAllFunc) appendCall(r0 StubWorldOsMkdirAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsMkdirAllFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsMkdirAllFunc) History() []StubWorldOsMkdirAllFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsMkdirAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsMkdirAllFuncCall is an object that describes an invocation of
// method OsMkdirAll on an instance of MockStubWorld.
type StubWorldOsMkdirAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 fs.FileMode
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsMkdirAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsMkdirAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsRemoveFunc describes the behavior when the OsRemove method of
// the parent MockStubWorld instance is invoked.
type StubWorldOsRemoveFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []StubWorldOsRemoveFuncCall
	mutex       sync.Mutex
}

// OsRemove delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorld) OsRemove(v0 string) error {
	r0 := m.OsRemoveFunc.nextHook()(v0)
	m.OsRemoveFunc.appendCall(StubWorldOsRemoveFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsRemove method of
// the parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldOsRemoveFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsRemove method of the parent MockStubWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsRemoveFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsRemoveFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsRemoveFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *StubWorldOsRemoveFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsRemoveFunc) appendCall(r0 StubWorldOsRemoveFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsRemoveFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsRemoveFunc) History() []StubWorldOsRemoveFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsRemoveFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsRemoveFuncCall is an object that describes an invocation of
// method OsRemove on an instance of MockStubWorld.
type StubWorldOsRemoveFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsRemoveFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsRemoveFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsRemoveAllFunc describes the behavior when the OsRemoveAll
// method of the parent MockStubWorld instance is invoked.
type StubWorldOsRemoveAllFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []StubWorldOsRemoveAllFuncCall
	mutex       sync.Mutex
}

// OsRemoveAll delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorld) OsRemoveAll(v0 string) error {
	r0 := m.OsRemoveAllFunc.nextHook()(v0)
	m.OsRemoveAllFunc.appendCall(StubWorldOsRemoveAllFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsRemoveAll method
// of the parent MockStubWorld instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsRemoveAllFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsRemoveAll method of the parent MockStubWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsRemoveAllFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsRemoveAllFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsRemoveAllFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *StubWorldOsRemoveAllFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsRemoveAllFunc) appendCall(r0 StubWorldOsRemoveAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsRemoveAllFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsRemoveAllFunc) History() []StubWorldOsRemoveAllFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsRemoveAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsRemoveAllFuncCall is an object that describes an invocation of
// method OsRemoveAll on an instance of MockStubWorld.
type StubWorldOsRemoveAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsRemoveAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsRemoveAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsStatFunc describes the behavior when the OsStat method of the
// parent MockStubWorld instance is invoked.
type StubWorldOsStatFunc struct {
	defaultHook func(string) (fs.FileInfo, error)
	hooks       []func(string) (fs.FileInfo, error)
	history     []StubWorldOsStatFuncCall
	mutex       sync.Mutex
}

// OsStat delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorld) OsStat(v0 string) (fs.FileInfo, error) {
	r0, r1 := m.OsStatFunc.nextHook()(v0)
	m.OsStatFunc.appendCall(StubWorldOsStatFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the OsStat method of the
// parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldOsStatFunc) SetDefaultHook(hook func(string) (fs.FileInfo, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsStat method of the parent MockStubWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsStatFunc) PushHook(hook func(string) (fs.FileInfo, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsStatFunc) SetDefaultReturn(r0 fs.FileInfo, r1 error) {
	f.SetDefaultHook(func(string) (fs.FileInfo, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsStatFunc) PushReturn(r0 fs.FileInfo, r1 error) {
	f.PushHook(func(string) (fs.FileInfo, error) {
		return r0, r1
	})
}

func (f *StubWorldOsStatFunc) nextHook() func(string) (fs.FileInfo, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsStatFunc) appendCall(r0 StubWorldOsStatFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsStatFuncCall objects describing
// the invocations of this function.
func (f *StubWorldOsStatFunc) History() []StubWorldOsStatFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsStatFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsStatFuncCall is an object that describes an invocation of
// method OsStat on an instance of MockStubWorld.
type StubWorldOsStatFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 fs.FileInfo
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsStatFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsStatFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// MockStubWorldOsFile is a mock implementation of the WorldOsFile interface
// (from the package github.com/powerman/ebpf-same-cgroup-mark/internal/app)
// used for unit testing.
type MockStubWorldOsFile struct {
	// CloseFunc is an instance of a mock function object controlling the
	// behavior of the method Close.
	CloseFunc *StubWorldOsFileCloseFunc
	// NameFunc is an instance of a mock function object controlling the
	// behavior of the method Name.
	NameFunc *StubWorldOsFileNameFunc
	// WriteFunc is an instance of a mock function object controlling the
	// behavior of the method Write.
	WriteFunc *StubWorldOsFileWriteFunc
}

// NewMockStubWorldOsFile creates a new mock of the WorldOsFile interface.
// All methods return zero values for all results, unless overwritten.
func NewMockStubWorldOsFile() *MockStubWorldOsFile {
	return &MockStubWorldOsFile{
		CloseFunc: &StubWorldOsFileCloseFunc{
			defaultHook: func() (r0 error) {
				return
			},
		},
		NameFunc: &StubWorldOsFileNameFunc{
			defaultHook: func() (r0 string) {
				return
			},
		},
		WriteFunc: &StubWorldOsFileWriteFunc{
			defaultHook: func([]byte) (r0 int, r1 error) {
				return
			},
		},
	}
}

// NewStrictMockStubWorldOsFile creates a new mock of the WorldOsFile
// interface. All methods panic on invocation, unless overwritten.
func NewStrictMockStubWorldOsFile() *MockStubWorldOsFile {
	return &MockStubWorldOsFile{
		CloseFunc: &StubWorldOsFileCloseFunc{
			defaultHook: func() error {
				panic("unexpected invocation of MockStubWorldOsFile.Close")
			},
		},
		NameFunc: &StubWorldOsFileNameFunc{
			defaultHook: func() string {
				panic("unexpected invocation of MockStubWorldOsFile.Name")
			},
		},
		WriteFunc: &StubWorldOsFileWriteFunc{
			defaultHook: func([]byte) (int, error) {
				panic("unexpected invocation of MockStubWorldOsFile.Write")
			},
		},
	}
}

// NewMockStubWorldOsFileFrom creates a new mock of the MockStubWorldOsFile
// interface. All methods delegate to the given implementation, unless
// overwritten.
func NewMockStubWorldOsFileFrom(i app.WorldOsFile) *MockStubWorldOsFile {
	return &MockStubWorldOsFile{
		CloseFunc: &StubWorldOsFileCloseFunc{
			defaultHook: i.Close,
		},
		NameFunc: &StubWorldOsFileNameFunc{
			defaultHook: i.Name,
		},
		WriteFunc: &StubWorldOsFileWriteFunc{
			defaultHook: i.Write,
		},
	}
}

// StubWorldOsFileCloseFunc describes the behavior when the Close method of
// the parent MockStubWorldOsFile instance is invoked.
type StubWorldOsFileCloseFunc struct {
	defaultHook func() error
	hooks       []func() error
	history     []StubWorldOsFileCloseFuncCall
	mutex       sync.Mutex
}

// Close delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldOsFile) Close() error {
	r0 := m.CloseFunc.nextHook()()
	m.CloseFunc.appendCall(StubWorldOsFileCloseFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Close method of the
// parent MockStubWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsFileCloseFunc) SetDefaultHook(hook func() error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Close method of the parent MockStubWorldOsFile instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsFileCloseFunc) PushHook(hook func() error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsFileCloseFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func() error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsFileCloseFunc) PushReturn(r0 error) {
	f.PushHook(func() error {
		return r0
	})
}

func (f *StubWorldOsFileCloseFunc) nextHook() func() error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsFileCloseFunc) appendCall(r0 StubWorldOsFileCloseFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsFileCloseFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsFileCloseFunc) History() []StubWorldOsFileCloseFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsFileCloseFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsFileCloseFuncCall is an object that describes an invocation of
// method Close on an instance of MockStubWorldOsFile.
type StubWorldOsFileCloseFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsFileCloseFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsFileCloseFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsFileNameFunc describes the behavior when the Name method of
// the parent MockStubWorldOsFile instance is invoked.
type StubWorldOsFileNameFunc struct {
	defaultHook func() string
	hooks       []func() string
	history     []StubWorldOsFileNameFuncCall
	mutex       sync.Mutex
}

// Name delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldOsFile) Name() string {
	r0 := m.NameFunc.nextHook()()
	m.NameFunc.appendCall(StubWorldOsFileNameFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Name method of the
// parent MockStubWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsFileNameFunc) SetDefaultHook(hook func() string) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Name method of the parent MockStubWorldOsFile instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsFileNameFunc) PushHook(hook func() string) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsFileNameFunc) SetDefaultReturn(r0 string) {
	f.SetDefaultHook(func() string {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsFileNameFunc) PushReturn(r0 string) {
	f.PushHook(func() string {
		return r0
	})
}

func (f *StubWorldOsFileNameFunc) nextHook() func() string {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsFileNameFunc) appendCall(r0 StubWorldOsFileNameFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsFileNameFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsFileNameFunc) History() []StubWorldOsFileNameFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsFileNameFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsFileNameFuncCall is an object that describes an invocation of
// method Name on an instance of MockStubWorldOsFile.
type StubWorldOsFileNameFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 string
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsFileNameFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsFileNameFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsFileWriteFunc describes the behavior when the Write method of
// the parent MockStubWorldOsFile instance is invoked.
type StubWorldOsFileWriteFunc struct {
	defaultHook func([]byte) (int, error)
	hooks       []func([]byte) (int, error)
	history     []StubWorldOsFileWriteFuncCall
	mutex       sync.Mutex
}

// Write delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldOsFile) Write(v0 []byte) (int, error) {
	r0, r1 := m.WriteFunc.nextHook()(v0)
	m.WriteFunc.appendCall(StubWorldOsFileWriteFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the Write method of the
// parent MockStubWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsFileWriteFunc) SetDefaultHook(hook func([]byte) (int, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Write method of the parent MockStubWorldOsFile instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsFileWriteFunc) PushHook(hook func([]byte) (int, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsFileWriteFunc) SetDefaultReturn(r0 int, r1 error) {
	f.SetDefaultHook(func([]byte) (int, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsFileWriteFunc) PushReturn(r0 int, r1 error) {
	f.PushHook(func([]byte) (int, error) {
		return r0, r1
	})
}

func (f *StubWorldOsFileWriteFunc) nextHook() func([]byte) (int, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsFileWriteFunc) appendCall(r0 StubWorldOsFileWriteFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsFileWriteFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsFileWriteFunc) History() []StubWorldOsFileWriteFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsFileWriteFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsFileWriteFuncCall is an object that describes an invocation of
// method Write on an instance of MockStubWorldOsFile.
type StubWorldOsFileWriteFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 []byte
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 int
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsFileWriteFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsFileWriteFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}
