// Code generated by MockGen. DO NOT EDIT.
// Source: port.go
//
// Generated by this command:
//
//	mockgen -package=internal -source=port.go -destination=../test/internal/mock.port.go
//

// Package internal is a generated GoMock package.
package internal

import (
	os "os"
	reflect "reflect"

	internal "github.com/powerman/ebpf-same-cgroup-mark/internal"
	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockApp) Load() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(error)
	return ret0
}

// Load indicates an expected call of Load.
func (mr *MockAppMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockApp)(nil).Load))
}

// SetMark mocks base method.
func (m_2 *MockApp) SetMark(m internal.Mark) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SetMark", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMark indicates an expected call of SetMark.
func (mr *MockAppMockRecorder) SetMark(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMark", reflect.TypeOf((*MockApp)(nil).SetMark), m)
}

// Unload mocks base method.
func (m *MockApp) Unload() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unload")
	ret0, _ := ret[0].(error)
	return ret0
}

// Unload indicates an expected call of Unload.
func (mr *MockAppMockRecorder) Unload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unload", reflect.TypeOf((*MockApp)(nil).Unload))
}

// MockWorld is a mock of World interface.
type MockWorld struct {
	ctrl     *gomock.Controller
	recorder *MockWorldMockRecorder
	isgomock struct{}
}

// MockWorldMockRecorder is the mock recorder for MockWorld.
type MockWorldMockRecorder struct {
	mock *MockWorld
}

// NewMockWorld creates a new mock instance.
func NewMockWorld(ctrl *gomock.Controller) *MockWorld {
	mock := &MockWorld{ctrl: ctrl}
	mock.recorder = &MockWorldMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorld) EXPECT() *MockWorldMockRecorder {
	return m.recorder
}

// BpftoolCgroupAttach mocks base method.
func (m *MockWorld) BpftoolCgroupAttach(cgroup, attachType, progPin string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BpftoolCgroupAttach", cgroup, attachType, progPin)
	ret0, _ := ret[0].(error)
	return ret0
}

// BpftoolCgroupAttach indicates an expected call of BpftoolCgroupAttach.
func (mr *MockWorldMockRecorder) BpftoolCgroupAttach(cgroup, attachType, progPin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BpftoolCgroupAttach", reflect.TypeOf((*MockWorld)(nil).BpftoolCgroupAttach), cgroup, attachType, progPin)
}

// BpftoolCgroupDetach mocks base method.
func (m *MockWorld) BpftoolCgroupDetach(cgroup, attachType, progPin string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BpftoolCgroupDetach", cgroup, attachType, progPin)
	ret0, _ := ret[0].(error)
	return ret0
}

// BpftoolCgroupDetach indicates an expected call of BpftoolCgroupDetach.
func (mr *MockWorldMockRecorder) BpftoolCgroupDetach(cgroup, attachType, progPin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BpftoolCgroupDetach", reflect.TypeOf((*MockWorld)(nil).BpftoolCgroupDetach), cgroup, attachType, progPin)
}

// BpftoolCgroupShow mocks base method.
func (m *MockWorld) BpftoolCgroupShow(cgroup string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BpftoolCgroupShow", cgroup)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BpftoolCgroupShow indicates an expected call of BpftoolCgroupShow.
func (mr *MockWorldMockRecorder) BpftoolCgroupShow(cgroup any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BpftoolCgroupShow", reflect.TypeOf((*MockWorld)(nil).BpftoolCgroupShow), cgroup)
}

// BpftoolMapUpdate mocks base method.
func (m *MockWorld) BpftoolMapUpdate(args ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BpftoolMapUpdate", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// BpftoolMapUpdate indicates an expected call of BpftoolMapUpdate.
func (mr *MockWorldMockRecorder) BpftoolMapUpdate(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BpftoolMapUpdate", reflect.TypeOf((*MockWorld)(nil).BpftoolMapUpdate), args...)
}

// BpftoolProgLoadAll mocks base method.
func (m *MockWorld) BpftoolProgLoadAll(bpfObjPath, bpffs, mapsDir string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BpftoolProgLoadAll", bpfObjPath, bpffs, mapsDir)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BpftoolProgLoadAll indicates an expected call of BpftoolProgLoadAll.
func (mr *MockWorldMockRecorder) BpftoolProgLoadAll(bpfObjPath, bpffs, mapsDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BpftoolProgLoadAll", reflect.TypeOf((*MockWorld)(nil).BpftoolProgLoadAll), bpfObjPath, bpffs, mapsDir)
}

// MountBPF mocks base method.
func (m *MockWorld) MountBPF(fstype, target string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MountBPF", fstype, target)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MountBPF indicates an expected call of MountBPF.
func (mr *MockWorldMockRecorder) MountBPF(fstype, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MountBPF", reflect.TypeOf((*MockWorld)(nil).MountBPF), fstype, target)
}

// Mountpoint mocks base method.
func (m *MockWorld) Mountpoint(dir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mountpoint", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mountpoint indicates an expected call of Mountpoint.
func (mr *MockWorldMockRecorder) Mountpoint(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mountpoint", reflect.TypeOf((*MockWorld)(nil).Mountpoint), dir)
}

// OsCreateTemp mocks base method.
func (m *MockWorld) OsCreateTemp(dir, pattern string) (internal.WorldOsFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsCreateTemp", dir, pattern)
	ret0, _ := ret[0].(internal.WorldOsFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OsCreateTemp indicates an expected call of OsCreateTemp.
func (mr *MockWorldMockRecorder) OsCreateTemp(dir, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsCreateTemp", reflect.TypeOf((*MockWorld)(nil).OsCreateTemp), dir, pattern)
}

// OsGeteuid mocks base method.
func (m *MockWorld) OsGeteuid() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsGeteuid")
	ret0, _ := ret[0].(int)
	return ret0
}

// OsGeteuid indicates an expected call of OsGeteuid.
func (mr *MockWorldMockRecorder) OsGeteuid() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsGeteuid", reflect.TypeOf((*MockWorld)(nil).OsGeteuid))
}

// OsMkdirAll mocks base method.
func (m *MockWorld) OsMkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsMkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// OsMkdirAll indicates an expected call of OsMkdirAll.
func (mr *MockWorldMockRecorder) OsMkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsMkdirAll", reflect.TypeOf((*MockWorld)(nil).OsMkdirAll), path, perm)
}

// OsRemove mocks base method.
func (m *MockWorld) OsRemove(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsRemove", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// OsRemove indicates an expected call of OsRemove.
func (mr *MockWorldMockRecorder) OsRemove(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsRemove", reflect.TypeOf((*MockWorld)(nil).OsRemove), name)
}

// OsRemoveAll mocks base method.
func (m *MockWorld) OsRemoveAll(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsRemoveAll", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// OsRemoveAll indicates an expected call of OsRemoveAll.
func (mr *MockWorldMockRecorder) OsRemoveAll(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsRemoveAll", reflect.TypeOf((*MockWorld)(nil).OsRemoveAll), path)
}

// OsStat mocks base method.
func (m *MockWorld) OsStat(name string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OsStat", name)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OsStat indicates an expected call of OsStat.
func (mr *MockWorldMockRecorder) OsStat(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OsStat", reflect.TypeOf((*MockWorld)(nil).OsStat), name)
}

// MockWorldOsFile is a mock of WorldOsFile interface.
type MockWorldOsFile struct {
	ctrl     *gomock.Controller
	recorder *MockWorldOsFileMockRecorder
	isgomock struct{}
}

// MockWorldOsFileMockRecorder is the mock recorder for MockWorldOsFile.
type MockWorldOsFileMockRecorder struct {
	mock *MockWorldOsFile
}

// NewMockWorldOsFile creates a new mock instance.
func NewMockWorldOsFile(ctrl *gomock.Controller) *MockWorldOsFile {
	mock := &MockWorldOsFile{ctrl: ctrl}
	mock.recorder = &MockWorldOsFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorldOsFile) EXPECT() *MockWorldOsFileMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWorldOsFile) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWorldOsFileMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWorldOsFile)(nil).Close))
}

// Name mocks base method.
func (m *MockWorldOsFile) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockWorldOsFileMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockWorldOsFile)(nil).Name))
}

// Write mocks base method.
func (m *MockWorldOsFile) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockWorldOsFileMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWorldOsFile)(nil).Write), p)
}
