// Code generated by go-mockgen 2.1.1; DO NOT EDIT.

package internal_test

import (
	worldcmds "github.com/powerman/ebpf-same-cgroup-mark/test/internal/worldcmds"
	"sync"
)

// MockWorldCmds is a mock implementation of the WorldCmds interface (from
// the package
// github.com/powerman/ebpf-same-cgroup-mark/test/internal/worldcmds) used
// for unit testing.
type MockWorldCmds struct {
	// BpftoolCgroupAttachFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupAttach.
	BpftoolCgroupAttachFunc *WorldCmdsBpftoolCgroupAttachFunc
	// BpftoolCgroupDetachFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupDetach.
	BpftoolCgroupDetachFunc *WorldCmdsBpftoolCgroupDetachFunc
	// BpftoolCgroupShowFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupShow.
	BpftoolCgroupShowFunc *WorldCmdsBpftoolCgroupShowFunc
	// BpftoolMapUpdateFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolMapUpdate.
	BpftoolMapUpdateFunc *WorldCmdsBpftoolMapUpdateFunc
	// BpftoolProgLoadAllFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolProgLoadAll.
	BpftoolProgLoadAllFunc *WorldCmdsBpftoolProgLoadAllFunc
	// MountBPFFunc is an instance of a mock function object controlling the
	// behavior of the method MountBPF.
	MountBPFFunc *WorldCmdsMountBPFFunc
	// MountpointFunc is an instance of a mock function object controlling
	// the behavior of the method Mountpoint.
	MountpointFunc *WorldCmdsMountpointFunc
}

// NewMockWorldCmds creates a new mock of the WorldCmds interface. All
// methods return zero values for all results, unless overwritten.
func NewMockWorldCmds() *MockWorldCmds {
	return &MockWorldCmds{
		BpftoolCgroupAttachFunc: &WorldCmdsBpftoolCgroupAttachFunc{
			defaultHook: func(string, string, string) (r0 error) {
				return
			},
		},
		BpftoolCgroupDetachFunc: &WorldCmdsBpftoolCgroupDetachFunc{
			defaultHook: func(string, string, string) (r0 error) {
				return
			},
		},
		BpftoolCgroupShowFunc: &WorldCmdsBpftoolCgroupShowFunc{
			defaultHook: func(string) (r0 []byte, r1 error) {
				return
			},
		},
		BpftoolMapUpdateFunc: &WorldCmdsBpftoolMapUpdateFunc{
			defaultHook: func(...string) (r0 error) {
				return
			},
		},
		BpftoolProgLoadAllFunc: &WorldCmdsBpftoolProgLoadAllFunc{
			defaultHook: func(string, string, string) (r0 []byte, r1 error) {
				return
			},
		},
		MountBPFFunc: &WorldCmdsMountBPFFunc{
			defaultHook: func(string, string) (r0 []byte, r1 error) {
				return
			},
		},
		MountpointFunc: &WorldCmdsMountpointFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
	}
}

// NewStrictMockWorldCmds creates a new mock of the WorldCmds interface. All
// methods panic on invocation, unless overwritten.
func NewStrictMockWorldCmds() *MockWorldCmds {
	return &MockWorldCmds{
		BpftoolCgroupAttachFunc: &WorldCmdsBpftoolCgroupAttachFunc{
			defaultHook: func(string, string, string) error {
				panic("unexpected invocation of MockWorldCmds.BpftoolCgroupAttach")
			},
		},
		BpftoolCgroupDetachFunc: &WorldCmdsBpftoolCgroupDetachFunc{
			defaultHook: func(string, string, string) error {
				panic("unexpected invocation of MockWorldCmds.BpftoolCgroupDetach")
			},
		},
		BpftoolCgroupShowFunc: &WorldCmdsBpftoolCgroupShowFunc{
			defaultHook: func(string) ([]byte, error) {
				panic("unexpected invocation of MockWorldCmds.BpftoolCgroupShow")
			},
		},
		BpftoolMapUpdateFunc: &WorldCmdsBpftoolMapUpdateFunc{
			defaultHook: func(...string) error {
				panic("unexpected invocation of MockWorldCmds.BpftoolMapUpdate")
			},
		},
		BpftoolProgLoadAllFunc: &WorldCmdsBpftoolProgLoadAllFunc{
			defaultHook: func(string, string, string) ([]byte, error) {
				panic("unexpected invocation of MockWorldCmds.BpftoolProgLoadAll")
			},
		},
		MountBPFFunc: &WorldCmdsMountBPFFunc{
			defaultHook: func(string, string) ([]byte, error) {
				panic("unexpected invocation of MockWorldCmds.MountBPF")
			},
		},
		MountpointFunc: &WorldCmdsMountpointFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockWorldCmds.Mountpoint")
			},
		},
	}
}

// NewMockWorldCmdsFrom creates a new mock of the MockWorldCmds interface.
// All methods delegate to the given implementation, unless overwritten.
func NewMockWorldCmdsFrom(i worldcmds.WorldCmds) *MockWorldCmds {
	return &MockWorldCmds{
		BpftoolCgroupAttachFunc: &WorldCmdsBpftoolCgroupAttachFunc{
			defaultHook: i.BpftoolCgroupAttach,
		},
		BpftoolCgroupDetachFunc: &WorldCmdsBpftoolCgroupDetachFunc{
			defaultHook: i.BpftoolCgroupDetach,
		},
		BpftoolCgroupShowFunc: &WorldCmdsBpftoolCgroupShowFunc{
			defaultHook: i.BpftoolCgroupShow,
		},
		BpftoolMapUpdateFunc: &WorldCmdsBpftoolMapUpdateFunc{
			defaultHook: i.BpftoolMapUpdate,
		},
		BpftoolProgLoadAllFunc: &WorldCmdsBpftoolProgLoadAllFunc{
			defaultHook: i.BpftoolProgLoadAll,
		},
		MountBPFFunc: &WorldCmdsMountBPFFunc{
			defaultHook: i.MountBPF,
		},
		MountpointFunc: &WorldCmdsMountpointFunc{
			defaultHook: i.Mountpoint,
		},
	}
}

// WorldCmdsBpftoolCgroupAttachFunc describes the behavior when the
// BpftoolCgroupAttach method of the parent MockWorldCmds instance is
// invoked.
type WorldCmdsBpftoolCgroupAttachFunc struct {
	defaultHook func(string, string, string) error
	hooks       []func(string, string, string) error
	history     []WorldCmdsBpftoolCgroupAttachFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupAttach delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockWorldCmds) BpftoolCgroupAttach(v0 string, v1 string, v2 string) error {
	r0 := m.BpftoolCgroupAttachFunc.nextHook()(v0, v1, v2)
	m.BpftoolCgroupAttachFunc.appendCall(WorldCmdsBpftoolCgroupAttachFuncCall{v0, v1, v2, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolCgroupAttach
// method of the parent MockWorldCmds instance is invoked and the hook queue
// is empty.
func (f *WorldCmdsBpftoolCgroupAttachFunc) SetDefaultHook(hook func(string, string, string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupAttach method of the parent MockWorldCmds instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *WorldCmdsBpftoolCgroupAttachFunc) PushHook(hook func(string, string, string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *WorldCmdsBpftoolCgroupAttachFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, string, string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *WorldCmdsBpftoolCgroupAttachFunc) PushReturn(r0 error) {
	f.PushHook(func(string, string, string) error {
		return r0
	})
}

func (f *WorldCmdsBpftoolCgroupAttachFunc) nextHook() func(string, string, string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *WorldCmdsBpftoolCgroupAttachFunc) appendCall(r0 WorldCmdsBpftoolCgroupAttachFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of WorldCmdsBpftoolCgroupAttachFuncCall
// objects describing the invocations of this function.
func (f *WorldCmdsBpftoolCgroupAttachFunc) History() []WorldCmdsBpftoolCgroupAttachFuncCall {
	f.mutex.Lock()
	history := make([]WorldCmdsBpftoolCgroupAttachFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// WorldCmdsBpftoolCgroupAttachFuncCall is an object that describes an
// invocation of method BpftoolCgroupAttach on an instance of MockWorldCmds.
type WorldCmdsBpftoolCgroupAttachFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c WorldCmdsBpftoolCgroupAttachFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c WorldCmdsBpftoolCgroupAttachFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// WorldCmdsBpftoolCgroupDetachFunc describes the behavior when the
// BpftoolCgroupDetach method of the parent MockWorldCmds instance is
// invoked.
type WorldCmdsBpftoolCgroupDetachFunc struct {
	defaultHook func(string, string, string) error
	hooks       []func(string, string, string) error
	history     []WorldCmdsBpftoolCgroupDetachFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupDetach delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockWorldCmds) BpftoolCgroupDetach(v0 string, v1 string, v2 string) error {
	r0 := m.BpftoolCgroupDetachFunc.nextHook()(v0, v1, v2)
	m.BpftoolCgroupDetachFunc.appendCall(WorldCmdsBpftoolCgroupDetachFuncCall{v0, v1, v2, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolCgroupDetach
// method of the parent MockWorldCmds instance is invoked and the hook queue
// is empty.
func (f *WorldCmdsBpftoolCgroupDetachFunc) SetDefaultHook(hook func(string, string, string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupDetach method of the parent MockWorldCmds instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *WorldCmdsBpftoolCgroupDetachFunc) PushHook(hook func(string, string, string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *WorldCmdsBpftoolCgroupDetachFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, string, string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *WorldCmdsBpftoolCgroupDetachFunc) PushReturn(r0 error) {
	f.PushHook(func(string, string, string) error {
		return r0
	})
}

func (f *WorldCmdsBpftoolCgroupDetachFunc) nextHook() func(string, string, string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *WorldCmdsBpftoolCgroupDetachFunc) appendCall(r0 WorldCmdsBpftoolCgroupDetachFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of WorldCmdsBpftoolCgroupDetachFuncCall
// objects describing the invocations of this function.
func (f *WorldCmdsBpftoolCgroupDetachFunc) History() []WorldCmdsBpftoolCgroupDetachFuncCall {
	f.mutex.Lock()
	history := make([]WorldCmdsBpftoolCgroupDetachFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// WorldCmdsBpftoolCgroupDetachFuncCall is an object that describes an
// invocation of method BpftoolCgroupDetach on an instance of MockWorldCmds.
type WorldCmdsBpftoolCgroupDetachFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c WorldCmdsBpftoolCgroupDetachFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c WorldCmdsBpftoolCgroupDetachFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// WorldCmdsBpftoolCgroupShowFunc describes the behavior when the
// BpftoolCgroupShow method of the parent MockWorldCmds instance is invoked.
type WorldCmdsBpftoolCgroupShowFunc struct {
	defaultHook func(string) ([]byte, error)
	hooks       []func(string) ([]byte, error)
	history     []WorldCmdsBpftoolCgroupShowFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupShow delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockWorldCmds) BpftoolCgroupShow(v0 string) ([]byte, error) {
	r0, r1 := m.BpftoolCgroupShowFunc.nextHook()(v0)
	m.BpftoolCgroupShowFunc.appendCall(WorldCmdsBpftoolCgroupShowFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the BpftoolCgroupShow
// method of the parent MockWorldCmds instance is invoked and the hook queue
// is empty.
func (f *WorldCmdsBpftoolCgroupShowFunc) SetDefaultHook(hook func(string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupShow method of the parent MockWorldCmds instance invokes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *WorldCmdsBpftoolCgroupShowFunc) PushHook(hook func(string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *WorldCmdsBpftoolCgroupShowFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *WorldCmdsBpftoolCgroupShowFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string) ([]byte, error) {
		return r0, r1
	})
}

func (f *WorldCmdsBpftoolCgroupShowFunc) nextHook() func(string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *WorldCmdsBpftoolCgroupShowFunc) appendCall(r0 WorldCmdsBpftoolCgroupShowFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of WorldCmdsBpftoolCgroupShowFuncCall objects
// describing the invocations of this function.
func (f *WorldCmdsBpftoolCgroupShowFunc) History() []WorldCmdsBpftoolCgroupShowFuncCall {
	f.mutex.Lock()
	history := make([]WorldCmdsBpftoolCgroupShowFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// WorldCmdsBpftoolCgroupShowFuncCall is an object that describes an
// invocation of method BpftoolCgroupShow on an instance of MockWorldCmds.
type WorldCmdsBpftoolCgroupShowFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c WorldCmdsBpftoolCgroupShowFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c WorldCmdsBpftoolCgroupShowFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// WorldCmdsBpftoolMapUpdateFunc describes the behavior when the
// BpftoolMapUpdate method of the parent MockWorldCmds instance is invoked.
type WorldCmdsBpftoolMapUpdateFunc struct {
	defaultHook func(...string) error
	hooks       []func(...string) error
	history     []WorldCmdsBpftoolMapUpdateFuncCall
	mutex       sync.Mutex
}

// BpftoolMapUpdate delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockWorldCmds) BpftoolMapUpdate(v0 ...string) error {
	r0 := m.BpftoolMapUpdateFunc.nextHook()(v0...)
	m.BpftoolMapUpdateFunc.appendCall(WorldCmdsBpftoolMapUpdateFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolMapUpdate
// method of the parent MockWorldCmds instance is invoked and the hook queue
// is empty.
func (f *WorldCmdsBpftoolMapUpdateFunc) SetDefaultHook(hook func(...string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolMapUpdate method of the parent MockWorldCmds instance invokes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *WorldCmdsBpftoolMapUpdateFunc) PushHook(hook func(...string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *WorldCmdsBpftoolMapUpdateFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(...string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *WorldCmdsBpftoolMapUpdateFunc) PushReturn(r0 error) {
	f.PushHook(func(...string) error {
		return r0
	})
}

func (f *WorldCmdsBpftoolMapUpdateFunc) nextHook() func(...string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *WorldCmdsBpftoolMapUpdateFunc) appendCall(r0 WorldCmdsBpftoolMapUpdateFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of WorldCmdsBpftoolMapUpdateFuncCall objects
// describing the invocations of this function.
func (f *WorldCmdsBpftoolMapUpdateFunc) History() []WorldCmdsBpftoolMapUpdateFuncCall {
	f.mutex.Lock()
	history := make([]WorldCmdsBpftoolMapUpdateFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// WorldCmdsBpftoolMapUpdateFuncCall is an object that describes an
// invocation of method BpftoolMapUpdate on an instance of MockWorldCmds.
type WorldCmdsBpftoolMapUpdateFuncCall struct {
	// Arg0 is a slice containing the values of the variadic arguments
	// passed to this method invocation.
	Arg0 []string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation. The variadic slice argument is flattened in this array such
// that one positional argument and three variadic arguments would result in
// a slice of four, not two.
func (c WorldCmdsBpftoolMapUpdateFuncCall) Args() []interface{} {
	trailing := []interface{}{}
	for _, val := range c.Arg0 {
		trailing = append(trailing, val)
	}

	return append([]interface{}{}, trailing...)
}

// Results returns an interface slice containing the results of this
// invocation.
func (c WorldCmdsBpftoolMapUpdateFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// WorldCmdsBpftoolProgLoadAllFunc describes the behavior when the
// BpftoolProgLoadAll method of the parent MockWorldCmds instance is
// invoked.
type WorldCmdsBpftoolProgLoadAllFunc struct {
	defaultHook func(string, string, string) ([]byte, error)
	hooks       []func(string, string, string) ([]byte, error)
	history     []WorldCmdsBpftoolProgLoadAllFuncCall
	mutex       sync.Mutex
}

// BpftoolProgLoadAll delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockWorldCmds) BpftoolProgLoadAll(v0 string, v1 string, v2 string) ([]byte, error) {
	r0, r1 := m.BpftoolProgLoadAllFunc.nextHook()(v0, v1, v2)
	m.BpftoolProgLoadAllFunc.appendCall(WorldCmdsBpftoolProgLoadAllFuncCall{v0, v1, v2, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the BpftoolProgLoadAll
// method of the parent MockWorldCmds instance is invoked and the hook queue
// is empty.
func (f *WorldCmdsBpftoolProgLoadAllFunc) SetDefaultHook(hook func(string, string, string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolProgLoadAll method of the parent MockWorldCmds instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *WorldCmdsBpftoolProgLoadAllFunc) PushHook(hook func(string, string, string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *WorldCmdsBpftoolProgLoadAllFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string, string, string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *WorldCmdsBpftoolProgLoadAllFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string, string, string) ([]byte, error) {
		return r0, r1
	})
}

func (f *WorldCmdsBpftoolProgLoadAllFunc) nextHook() func(string, string, string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *WorldCmdsBpftoolProgLoadAllFunc) appendCall(r0 WorldCmdsBpftoolProgLoadAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of WorldCmdsBpftoolProgLoadAllFuncCall objects
// describing the invocations of this function.
func (f *WorldCmdsBpftoolProgLoadAllFunc) History() []WorldCmdsBpftoolProgLoadAllFuncCall {
	f.mutex.Lock()
	history := make([]WorldCmdsBpftoolProgLoadAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// WorldCmdsBpftoolProgLoadAllFuncCall is an object that describes an
// invocation of method BpftoolProgLoadAll on an instance of MockWorldCmds.
type WorldCmdsBpftoolProgLoadAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c WorldCmdsBpftoolProgLoadAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c WorldCmdsBpftoolProgLoadAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// WorldCmdsMountBPFFunc describes the behavior when the MountBPF method of
// the parent MockWorldCmds instance is invoked.
type WorldCmdsMountBPFFunc struct {
	defaultHook func(string, string) ([]byte, error)
	hooks       []func(string, string) ([]byte, error)
	history     []WorldCmdsMountBPFFuncCall
	mutex       sync.Mutex
}

// MountBPF delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockWorldCmds) MountBPF(v0 string, v1 string) ([]byte, error) {
	r0, r1 := m.MountBPFFunc.nextHook()(v0, v1)
	m.MountBPFFunc.appendCall(WorldCmdsMountBPFFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the MountBPF method of
// the parent MockWorldCmds instance is invoked and the hook queue is empty.
func (f *WorldCmdsMountBPFFunc) SetDefaultHook(hook func(string, string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// MountBPF method of the parent MockWorldCmds instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *WorldCmdsMountBPFFunc) PushHook(hook func(string, string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *WorldCmdsMountBPFFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string, string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *WorldCmdsMountBPFFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string, string) ([]byte, error) {
		return r0, r1
	})
}

func (f *WorldCmdsMountBPFFunc) nextHook() func(string, string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *WorldCmdsMountBPFFunc) appendCall(r0 WorldCmdsMountBPFFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of WorldCmdsMountBPFFuncCall objects
// describing the invocations of this function.
func (f *WorldCmdsMountBPFFunc) History() []WorldCmdsMountBPFFuncCall {
	f.mutex.Lock()
	history := make([]WorldCmdsMountBPFFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// WorldCmdsMountBPFFuncCall is an object that describes an invocation of
// method MountBPF on an instance of MockWorldCmds.
type WorldCmdsMountBPFFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c WorldCmdsMountBPFFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c WorldCmdsMountBPFFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// WorldCmdsMountpointFunc describes the behavior when the Mountpoint method
// of the parent MockWorldCmds instance is invoked.
type WorldCmdsMountpointFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []WorldCmdsMountpointFuncCall
	mutex       sync.Mutex
}

// Mountpoint delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockWorldCmds) Mountpoint(v0 string) error {
	r0 := m.MountpointFunc.nextHook()(v0)
	m.MountpointFunc.appendCall(WorldCmdsMountpointFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the Mountpoint method of
// the parent MockWorldCmds instance is invoked and the hook queue is empty.
func (f *WorldCmdsMountpointFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Mountpoint method of the parent MockWorldCmds instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *WorldCmdsMountpointFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *WorldCmdsMountpointFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *WorldCmdsMountpointFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *WorldCmdsMountpointFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *WorldCmdsMountpointFunc) appendCall(r0 WorldCmdsMountpointFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of WorldCmdsMountpointFuncCall objects
// describing the invocations of this function.
func (f *WorldCmdsMountpointFunc) History() []WorldCmdsMountpointFuncCall {
	f.mutex.Lock()
	history := make([]WorldCmdsMountpointFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// WorldCmdsMountpointFuncCall is an object that describes an invocation of
// method Mountpoint on an instance of MockWorldCmds.
type WorldCmdsMountpointFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c WorldCmdsMountpointFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c WorldCmdsMountpointFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}
