// Code generated by go-mockgen 2.1.1; DO NOT EDIT.

package internal_test

import (
	"io/fs"
	"sync"

	internal "github.com/powerman/ebpf-same-cgroup-mark/internal"
)

// MockgenWorld is a mock implementation of the World interface (from the
// package github.com/powerman/ebpf-same-cgroup-mark/internal) used for unit
// testing.
type MockgenWorld struct {
	// ExecCommandFunc is an instance of a mock function object controlling
	// the behavior of the method ExecCommand.
	ExecCommandFunc *genWorldExecCommandFunc
	// OsCreateTempFunc is an instance of a mock function object controlling
	// the behavior of the method OsCreateTemp.
	OsCreateTempFunc *genWorldOsCreateTempFunc
	// OsGeteuidFunc is an instance of a mock function object controlling
	// the behavior of the method OsGeteuid.
	OsGeteuidFunc *genWorldOsGeteuidFunc
	// OsMkdirAllFunc is an instance of a mock function object controlling
	// the behavior of the method OsMkdirAll.
	OsMkdirAllFunc *genWorldOsMkdirAllFunc
	// OsRemoveFunc is an instance of a mock function object controlling the
	// behavior of the method OsRemove.
	OsRemoveFunc *genWorldOsRemoveFunc
	// OsRemoveAllFunc is an instance of a mock function object controlling
	// the behavior of the method OsRemoveAll.
	OsRemoveAllFunc *genWorldOsRemoveAllFunc
	// OsStatFunc is an instance of a mock function object controlling the
	// behavior of the method OsStat.
	OsStatFunc *genWorldOsStatFunc
}

// NewMockgenWorld creates a new mock of the World interface. All methods
// return zero values for all results, unless overwritten.
func NewMockgenWorld() *MockgenWorld {
	return &MockgenWorld{
		ExecCommandFunc: &genWorldExecCommandFunc{
			defaultHook: func(string, ...string) (r0 internal.WorldExecCmd) {
				return
			},
		},
		OsCreateTempFunc: &genWorldOsCreateTempFunc{
			defaultHook: func(string, string) (r0 internal.WorldOsFile, r1 error) {
				return
			},
		},
		OsGeteuidFunc: &genWorldOsGeteuidFunc{
			defaultHook: func() (r0 int) {
				return
			},
		},
		OsMkdirAllFunc: &genWorldOsMkdirAllFunc{
			defaultHook: func(string, fs.FileMode) (r0 error) {
				return
			},
		},
		OsRemoveFunc: &genWorldOsRemoveFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
		OsRemoveAllFunc: &genWorldOsRemoveAllFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
		OsStatFunc: &genWorldOsStatFunc{
			defaultHook: func(string) (r0 fs.FileInfo, r1 error) {
				return
			},
		},
	}
}

// NewStrictMockgenWorld creates a new mock of the World interface. All
// methods panic on invocation, unless overwritten.
func NewStrictMockgenWorld() *MockgenWorld {
	return &MockgenWorld{
		ExecCommandFunc: &genWorldExecCommandFunc{
			defaultHook: func(string, ...string) internal.WorldExecCmd {
				panic("unexpected invocation of MockgenWorld.ExecCommand")
			},
		},
		OsCreateTempFunc: &genWorldOsCreateTempFunc{
			defaultHook: func(string, string) (internal.WorldOsFile, error) {
				panic("unexpected invocation of MockgenWorld.OsCreateTemp")
			},
		},
		OsGeteuidFunc: &genWorldOsGeteuidFunc{
			defaultHook: func() int {
				panic("unexpected invocation of MockgenWorld.OsGeteuid")
			},
		},
		OsMkdirAllFunc: &genWorldOsMkdirAllFunc{
			defaultHook: func(string, fs.FileMode) error {
				panic("unexpected invocation of MockgenWorld.OsMkdirAll")
			},
		},
		OsRemoveFunc: &genWorldOsRemoveFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockgenWorld.OsRemove")
			},
		},
		OsRemoveAllFunc: &genWorldOsRemoveAllFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockgenWorld.OsRemoveAll")
			},
		},
		OsStatFunc: &genWorldOsStatFunc{
			defaultHook: func(string) (fs.FileInfo, error) {
				panic("unexpected invocation of MockgenWorld.OsStat")
			},
		},
	}
}

// NewMockgenWorldFrom creates a new mock of the MockgenWorld interface. All
// methods delegate to the given implementation, unless overwritten.
func NewMockgenWorldFrom(i internal.World) *MockgenWorld {
	return &MockgenWorld{
		ExecCommandFunc: &genWorldExecCommandFunc{
			defaultHook: i.ExecCommand,
		},
		OsCreateTempFunc: &genWorldOsCreateTempFunc{
			defaultHook: i.OsCreateTemp,
		},
		OsGeteuidFunc: &genWorldOsGeteuidFunc{
			defaultHook: i.OsGeteuid,
		},
		OsMkdirAllFunc: &genWorldOsMkdirAllFunc{
			defaultHook: i.OsMkdirAll,
		},
		OsRemoveFunc: &genWorldOsRemoveFunc{
			defaultHook: i.OsRemove,
		},
		OsRemoveAllFunc: &genWorldOsRemoveAllFunc{
			defaultHook: i.OsRemoveAll,
		},
		OsStatFunc: &genWorldOsStatFunc{
			defaultHook: i.OsStat,
		},
	}
}

// genWorldExecCommandFunc describes the behavior when the ExecCommand
// method of the parent MockgenWorld instance is invoked.
type genWorldExecCommandFunc struct {
	defaultHook func(string, ...string) internal.WorldExecCmd
	hooks       []func(string, ...string) internal.WorldExecCmd
	history     []genWorldExecCommandFuncCall
	mutex       sync.Mutex
}

// ExecCommand delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockgenWorld) ExecCommand(v0 string, v1 ...string) internal.WorldExecCmd {
	r0 := m.ExecCommandFunc.nextHook()(v0, v1...)
	m.ExecCommandFunc.appendCall(genWorldExecCommandFuncCall{v0, v1, r0})
	return r0
}

// SetDefaultHook sets function that is called when the ExecCommand method
// of the parent MockgenWorld instance is invoked and the hook queue is
// empty.
func (f *genWorldExecCommandFunc) SetDefaultHook(hook func(string, ...string) internal.WorldExecCmd) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// ExecCommand method of the parent MockgenWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldExecCommandFunc) PushHook(hook func(string, ...string) internal.WorldExecCmd) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldExecCommandFunc) SetDefaultReturn(r0 internal.WorldExecCmd) {
	f.SetDefaultHook(func(string, ...string) internal.WorldExecCmd {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldExecCommandFunc) PushReturn(r0 internal.WorldExecCmd) {
	f.PushHook(func(string, ...string) internal.WorldExecCmd {
		return r0
	})
}

func (f *genWorldExecCommandFunc) nextHook() func(string, ...string) internal.WorldExecCmd {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldExecCommandFunc) appendCall(r0 genWorldExecCommandFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldExecCommandFuncCall objects
// describing the invocations of this function.
func (f *genWorldExecCommandFunc) History() []genWorldExecCommandFuncCall {
	f.mutex.Lock()
	history := make([]genWorldExecCommandFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldExecCommandFuncCall is an object that describes an invocation of
// method ExecCommand on an instance of MockgenWorld.
type genWorldExecCommandFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is a slice containing the values of the variadic arguments
	// passed to this method invocation.
	Arg1 []string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 internal.WorldExecCmd
}

// Args returns an interface slice containing the arguments of this
// invocation. The variadic slice argument is flattened in this array such
// that one positional argument and three variadic arguments would result in
// a slice of four, not two.
func (c genWorldExecCommandFuncCall) Args() []interface{} {
	trailing := []interface{}{}
	for _, val := range c.Arg1 {
		trailing = append(trailing, val)
	}

	return append([]interface{}{c.Arg0}, trailing...)
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldExecCommandFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// genWorldOsCreateTempFunc describes the behavior when the OsCreateTemp
// method of the parent MockgenWorld instance is invoked.
type genWorldOsCreateTempFunc struct {
	defaultHook func(string, string) (internal.WorldOsFile, error)
	hooks       []func(string, string) (internal.WorldOsFile, error)
	history     []genWorldOsCreateTempFuncCall
	mutex       sync.Mutex
}

// OsCreateTemp delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockgenWorld) OsCreateTemp(v0 string, v1 string) (internal.WorldOsFile, error) {
	r0, r1 := m.OsCreateTempFunc.nextHook()(v0, v1)
	m.OsCreateTempFunc.appendCall(genWorldOsCreateTempFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the OsCreateTemp method
// of the parent MockgenWorld instance is invoked and the hook queue is
// empty.
func (f *genWorldOsCreateTempFunc) SetDefaultHook(hook func(string, string) (internal.WorldOsFile, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsCreateTemp method of the parent MockgenWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldOsCreateTempFunc) PushHook(hook func(string, string) (internal.WorldOsFile, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsCreateTempFunc) SetDefaultReturn(r0 internal.WorldOsFile, r1 error) {
	f.SetDefaultHook(func(string, string) (internal.WorldOsFile, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsCreateTempFunc) PushReturn(r0 internal.WorldOsFile, r1 error) {
	f.PushHook(func(string, string) (internal.WorldOsFile, error) {
		return r0, r1
	})
}

func (f *genWorldOsCreateTempFunc) nextHook() func(string, string) (internal.WorldOsFile, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsCreateTempFunc) appendCall(r0 genWorldOsCreateTempFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsCreateTempFuncCall objects
// describing the invocations of this function.
func (f *genWorldOsCreateTempFunc) History() []genWorldOsCreateTempFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsCreateTempFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsCreateTempFuncCall is an object that describes an invocation of
// method OsCreateTemp on an instance of MockgenWorld.
type genWorldOsCreateTempFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 internal.WorldOsFile
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsCreateTempFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsCreateTempFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// genWorldOsGeteuidFunc describes the behavior when the OsGeteuid method of
// the parent MockgenWorld instance is invoked.
type genWorldOsGeteuidFunc struct {
	defaultHook func() int
	hooks       []func() int
	history     []genWorldOsGeteuidFuncCall
	mutex       sync.Mutex
}

// OsGeteuid delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockgenWorld) OsGeteuid() int {
	r0 := m.OsGeteuidFunc.nextHook()()
	m.OsGeteuidFunc.appendCall(genWorldOsGeteuidFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsGeteuid method of
// the parent MockgenWorld instance is invoked and the hook queue is empty.
func (f *genWorldOsGeteuidFunc) SetDefaultHook(hook func() int) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsGeteuid method of the parent MockgenWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldOsGeteuidFunc) PushHook(hook func() int) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsGeteuidFunc) SetDefaultReturn(r0 int) {
	f.SetDefaultHook(func() int {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsGeteuidFunc) PushReturn(r0 int) {
	f.PushHook(func() int {
		return r0
	})
}

func (f *genWorldOsGeteuidFunc) nextHook() func() int {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsGeteuidFunc) appendCall(r0 genWorldOsGeteuidFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsGeteuidFuncCall objects
// describing the invocations of this function.
func (f *genWorldOsGeteuidFunc) History() []genWorldOsGeteuidFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsGeteuidFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsGeteuidFuncCall is an object that describes an invocation of
// method OsGeteuid on an instance of MockgenWorld.
type genWorldOsGeteuidFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 int
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsGeteuidFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsGeteuidFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// genWorldOsMkdirAllFunc describes the behavior when the OsMkdirAll method
// of the parent MockgenWorld instance is invoked.
type genWorldOsMkdirAllFunc struct {
	defaultHook func(string, fs.FileMode) error
	hooks       []func(string, fs.FileMode) error
	history     []genWorldOsMkdirAllFuncCall
	mutex       sync.Mutex
}

// OsMkdirAll delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockgenWorld) OsMkdirAll(v0 string, v1 fs.FileMode) error {
	r0 := m.OsMkdirAllFunc.nextHook()(v0, v1)
	m.OsMkdirAllFunc.appendCall(genWorldOsMkdirAllFuncCall{v0, v1, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsMkdirAll method of
// the parent MockgenWorld instance is invoked and the hook queue is empty.
func (f *genWorldOsMkdirAllFunc) SetDefaultHook(hook func(string, fs.FileMode) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsMkdirAll method of the parent MockgenWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldOsMkdirAllFunc) PushHook(hook func(string, fs.FileMode) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsMkdirAllFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, fs.FileMode) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsMkdirAllFunc) PushReturn(r0 error) {
	f.PushHook(func(string, fs.FileMode) error {
		return r0
	})
}

func (f *genWorldOsMkdirAllFunc) nextHook() func(string, fs.FileMode) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsMkdirAllFunc) appendCall(r0 genWorldOsMkdirAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsMkdirAllFuncCall objects
// describing the invocations of this function.
func (f *genWorldOsMkdirAllFunc) History() []genWorldOsMkdirAllFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsMkdirAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsMkdirAllFuncCall is an object that describes an invocation of
// method OsMkdirAll on an instance of MockgenWorld.
type genWorldOsMkdirAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 fs.FileMode
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsMkdirAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsMkdirAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// genWorldOsRemoveFunc describes the behavior when the OsRemove method of
// the parent MockgenWorld instance is invoked.
type genWorldOsRemoveFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []genWorldOsRemoveFuncCall
	mutex       sync.Mutex
}

// OsRemove delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockgenWorld) OsRemove(v0 string) error {
	r0 := m.OsRemoveFunc.nextHook()(v0)
	m.OsRemoveFunc.appendCall(genWorldOsRemoveFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsRemove method of
// the parent MockgenWorld instance is invoked and the hook queue is empty.
func (f *genWorldOsRemoveFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsRemove method of the parent MockgenWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldOsRemoveFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsRemoveFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsRemoveFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *genWorldOsRemoveFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsRemoveFunc) appendCall(r0 genWorldOsRemoveFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsRemoveFuncCall objects describing
// the invocations of this function.
func (f *genWorldOsRemoveFunc) History() []genWorldOsRemoveFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsRemoveFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsRemoveFuncCall is an object that describes an invocation of
// method OsRemove on an instance of MockgenWorld.
type genWorldOsRemoveFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsRemoveFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsRemoveFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// genWorldOsRemoveAllFunc describes the behavior when the OsRemoveAll
// method of the parent MockgenWorld instance is invoked.
type genWorldOsRemoveAllFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []genWorldOsRemoveAllFuncCall
	mutex       sync.Mutex
}

// OsRemoveAll delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockgenWorld) OsRemoveAll(v0 string) error {
	r0 := m.OsRemoveAllFunc.nextHook()(v0)
	m.OsRemoveAllFunc.appendCall(genWorldOsRemoveAllFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsRemoveAll method
// of the parent MockgenWorld instance is invoked and the hook queue is
// empty.
func (f *genWorldOsRemoveAllFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsRemoveAll method of the parent MockgenWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldOsRemoveAllFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsRemoveAllFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsRemoveAllFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *genWorldOsRemoveAllFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsRemoveAllFunc) appendCall(r0 genWorldOsRemoveAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsRemoveAllFuncCall objects
// describing the invocations of this function.
func (f *genWorldOsRemoveAllFunc) History() []genWorldOsRemoveAllFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsRemoveAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsRemoveAllFuncCall is an object that describes an invocation of
// method OsRemoveAll on an instance of MockgenWorld.
type genWorldOsRemoveAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsRemoveAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsRemoveAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// genWorldOsStatFunc describes the behavior when the OsStat method of the
// parent MockgenWorld instance is invoked.
type genWorldOsStatFunc struct {
	defaultHook func(string) (fs.FileInfo, error)
	hooks       []func(string) (fs.FileInfo, error)
	history     []genWorldOsStatFuncCall
	mutex       sync.Mutex
}

// OsStat delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockgenWorld) OsStat(v0 string) (fs.FileInfo, error) {
	r0, r1 := m.OsStatFunc.nextHook()(v0)
	m.OsStatFunc.appendCall(genWorldOsStatFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the OsStat method of the
// parent MockgenWorld instance is invoked and the hook queue is empty.
func (f *genWorldOsStatFunc) SetDefaultHook(hook func(string) (fs.FileInfo, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsStat method of the parent MockgenWorld instance invokes the hook at the
// front of the queue and discards it. After the queue is empty, the default
// hook function is invoked for any future action.
func (f *genWorldOsStatFunc) PushHook(hook func(string) (fs.FileInfo, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsStatFunc) SetDefaultReturn(r0 fs.FileInfo, r1 error) {
	f.SetDefaultHook(func(string) (fs.FileInfo, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsStatFunc) PushReturn(r0 fs.FileInfo, r1 error) {
	f.PushHook(func(string) (fs.FileInfo, error) {
		return r0, r1
	})
}

func (f *genWorldOsStatFunc) nextHook() func(string) (fs.FileInfo, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsStatFunc) appendCall(r0 genWorldOsStatFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsStatFuncCall objects describing
// the invocations of this function.
func (f *genWorldOsStatFunc) History() []genWorldOsStatFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsStatFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsStatFuncCall is an object that describes an invocation of
// method OsStat on an instance of MockgenWorld.
type genWorldOsStatFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 fs.FileInfo
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsStatFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsStatFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// MockgenWorldExecCmd is a mock implementation of the WorldExecCmd
// interface (from the package
// github.com/powerman/ebpf-same-cgroup-mark/internal) used for unit
// testing.
type MockgenWorldExecCmd struct {
	// CombinedOutputFunc is an instance of a mock function object
	// controlling the behavior of the method CombinedOutput.
	CombinedOutputFunc *genWorldExecCmdCombinedOutputFunc
	// OutputFunc is an instance of a mock function object controlling the
	// behavior of the method Output.
	OutputFunc *genWorldExecCmdOutputFunc
	// RunFunc is an instance of a mock function object controlling the
	// behavior of the method Run.
	RunFunc *genWorldExecCmdRunFunc
}

// NewMockgenWorldExecCmd creates a new mock of the WorldExecCmd interface.
// All methods return zero values for all results, unless overwritten.
func NewMockgenWorldExecCmd() *MockgenWorldExecCmd {
	return &MockgenWorldExecCmd{
		CombinedOutputFunc: &genWorldExecCmdCombinedOutputFunc{
			defaultHook: func() (r0 []byte, r1 error) {
				return
			},
		},
		OutputFunc: &genWorldExecCmdOutputFunc{
			defaultHook: func() (r0 []byte, r1 error) {
				return
			},
		},
		RunFunc: &genWorldExecCmdRunFunc{
			defaultHook: func() (r0 error) {
				return
			},
		},
	}
}

// NewStrictMockgenWorldExecCmd creates a new mock of the WorldExecCmd
// interface. All methods panic on invocation, unless overwritten.
func NewStrictMockgenWorldExecCmd() *MockgenWorldExecCmd {
	return &MockgenWorldExecCmd{
		CombinedOutputFunc: &genWorldExecCmdCombinedOutputFunc{
			defaultHook: func() ([]byte, error) {
				panic("unexpected invocation of MockgenWorldExecCmd.CombinedOutput")
			},
		},
		OutputFunc: &genWorldExecCmdOutputFunc{
			defaultHook: func() ([]byte, error) {
				panic("unexpected invocation of MockgenWorldExecCmd.Output")
			},
		},
		RunFunc: &genWorldExecCmdRunFunc{
			defaultHook: func() error {
				panic("unexpected invocation of MockgenWorldExecCmd.Run")
			},
		},
	}
}

// NewMockgenWorldExecCmdFrom creates a new mock of the MockgenWorldExecCmd
// interface. All methods delegate to the given implementation, unless
// overwritten.
func NewMockgenWorldExecCmdFrom(i internal.WorldExecCmd) *MockgenWorldExecCmd {
	return &MockgenWorldExecCmd{
		CombinedOutputFunc: &genWorldExecCmdCombinedOutputFunc{
			defaultHook: i.CombinedOutput,
		},
		OutputFunc: &genWorldExecCmdOutputFunc{
			defaultHook: i.Output,
		},
		RunFunc: &genWorldExecCmdRunFunc{
			defaultHook: i.Run,
		},
	}
}

// genWorldExecCmdCombinedOutputFunc describes the behavior when the
// CombinedOutput method of the parent MockgenWorldExecCmd instance is
// invoked.
type genWorldExecCmdCombinedOutputFunc struct {
	defaultHook func() ([]byte, error)
	hooks       []func() ([]byte, error)
	history     []genWorldExecCmdCombinedOutputFuncCall
	mutex       sync.Mutex
}

// CombinedOutput delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockgenWorldExecCmd) CombinedOutput() ([]byte, error) {
	r0, r1 := m.CombinedOutputFunc.nextHook()()
	m.CombinedOutputFunc.appendCall(genWorldExecCmdCombinedOutputFuncCall{r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the CombinedOutput
// method of the parent MockgenWorldExecCmd instance is invoked and the hook
// queue is empty.
func (f *genWorldExecCmdCombinedOutputFunc) SetDefaultHook(hook func() ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// CombinedOutput method of the parent MockgenWorldExecCmd instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *genWorldExecCmdCombinedOutputFunc) PushHook(hook func() ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldExecCmdCombinedOutputFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func() ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldExecCmdCombinedOutputFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func() ([]byte, error) {
		return r0, r1
	})
}

func (f *genWorldExecCmdCombinedOutputFunc) nextHook() func() ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldExecCmdCombinedOutputFunc) appendCall(r0 genWorldExecCmdCombinedOutputFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldExecCmdCombinedOutputFuncCall
// objects describing the invocations of this function.
func (f *genWorldExecCmdCombinedOutputFunc) History() []genWorldExecCmdCombinedOutputFuncCall {
	f.mutex.Lock()
	history := make([]genWorldExecCmdCombinedOutputFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldExecCmdCombinedOutputFuncCall is an object that describes an
// invocation of method CombinedOutput on an instance of
// MockgenWorldExecCmd.
type genWorldExecCmdCombinedOutputFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldExecCmdCombinedOutputFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldExecCmdCombinedOutputFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// genWorldExecCmdOutputFunc describes the behavior when the Output method
// of the parent MockgenWorldExecCmd instance is invoked.
type genWorldExecCmdOutputFunc struct {
	defaultHook func() ([]byte, error)
	hooks       []func() ([]byte, error)
	history     []genWorldExecCmdOutputFuncCall
	mutex       sync.Mutex
}

// Output delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockgenWorldExecCmd) Output() ([]byte, error) {
	r0, r1 := m.OutputFunc.nextHook()()
	m.OutputFunc.appendCall(genWorldExecCmdOutputFuncCall{r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the Output method of the
// parent MockgenWorldExecCmd instance is invoked and the hook queue is
// empty.
func (f *genWorldExecCmdOutputFunc) SetDefaultHook(hook func() ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Output method of the parent MockgenWorldExecCmd instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldExecCmdOutputFunc) PushHook(hook func() ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldExecCmdOutputFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func() ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldExecCmdOutputFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func() ([]byte, error) {
		return r0, r1
	})
}

func (f *genWorldExecCmdOutputFunc) nextHook() func() ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldExecCmdOutputFunc) appendCall(r0 genWorldExecCmdOutputFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldExecCmdOutputFuncCall objects
// describing the invocations of this function.
func (f *genWorldExecCmdOutputFunc) History() []genWorldExecCmdOutputFuncCall {
	f.mutex.Lock()
	history := make([]genWorldExecCmdOutputFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldExecCmdOutputFuncCall is an object that describes an invocation
// of method Output on an instance of MockgenWorldExecCmd.
type genWorldExecCmdOutputFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldExecCmdOutputFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldExecCmdOutputFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// genWorldExecCmdRunFunc describes the behavior when the Run method of the
// parent MockgenWorldExecCmd instance is invoked.
type genWorldExecCmdRunFunc struct {
	defaultHook func() error
	hooks       []func() error
	history     []genWorldExecCmdRunFuncCall
	mutex       sync.Mutex
}

// Run delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockgenWorldExecCmd) Run() error {
	r0 := m.RunFunc.nextHook()()
	m.RunFunc.appendCall(genWorldExecCmdRunFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Run method of the
// parent MockgenWorldExecCmd instance is invoked and the hook queue is
// empty.
func (f *genWorldExecCmdRunFunc) SetDefaultHook(hook func() error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Run method of the parent MockgenWorldExecCmd instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldExecCmdRunFunc) PushHook(hook func() error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldExecCmdRunFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func() error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldExecCmdRunFunc) PushReturn(r0 error) {
	f.PushHook(func() error {
		return r0
	})
}

func (f *genWorldExecCmdRunFunc) nextHook() func() error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldExecCmdRunFunc) appendCall(r0 genWorldExecCmdRunFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldExecCmdRunFuncCall objects
// describing the invocations of this function.
func (f *genWorldExecCmdRunFunc) History() []genWorldExecCmdRunFuncCall {
	f.mutex.Lock()
	history := make([]genWorldExecCmdRunFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldExecCmdRunFuncCall is an object that describes an invocation of
// method Run on an instance of MockgenWorldExecCmd.
type genWorldExecCmdRunFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldExecCmdRunFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldExecCmdRunFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// MockgenWorldOsFile is a mock implementation of the WorldOsFile interface
// (from the package github.com/powerman/ebpf-same-cgroup-mark/internal)
// used for unit testing.
type MockgenWorldOsFile struct {
	// CloseFunc is an instance of a mock function object controlling the
	// behavior of the method Close.
	CloseFunc *genWorldOsFileCloseFunc
	// NameFunc is an instance of a mock function object controlling the
	// behavior of the method Name.
	NameFunc *genWorldOsFileNameFunc
	// WriteFunc is an instance of a mock function object controlling the
	// behavior of the method Write.
	WriteFunc *genWorldOsFileWriteFunc
}

// NewMockgenWorldOsFile creates a new mock of the WorldOsFile interface.
// All methods return zero values for all results, unless overwritten.
func NewMockgenWorldOsFile() *MockgenWorldOsFile {
	return &MockgenWorldOsFile{
		CloseFunc: &genWorldOsFileCloseFunc{
			defaultHook: func() (r0 error) {
				return
			},
		},
		NameFunc: &genWorldOsFileNameFunc{
			defaultHook: func() (r0 string) {
				return
			},
		},
		WriteFunc: &genWorldOsFileWriteFunc{
			defaultHook: func([]byte) (r0 int, r1 error) {
				return
			},
		},
	}
}

// NewStrictMockgenWorldOsFile creates a new mock of the WorldOsFile
// interface. All methods panic on invocation, unless overwritten.
func NewStrictMockgenWorldOsFile() *MockgenWorldOsFile {
	return &MockgenWorldOsFile{
		CloseFunc: &genWorldOsFileCloseFunc{
			defaultHook: func() error {
				panic("unexpected invocation of MockgenWorldOsFile.Close")
			},
		},
		NameFunc: &genWorldOsFileNameFunc{
			defaultHook: func() string {
				panic("unexpected invocation of MockgenWorldOsFile.Name")
			},
		},
		WriteFunc: &genWorldOsFileWriteFunc{
			defaultHook: func([]byte) (int, error) {
				panic("unexpected invocation of MockgenWorldOsFile.Write")
			},
		},
	}
}

// NewMockgenWorldOsFileFrom creates a new mock of the MockgenWorldOsFile
// interface. All methods delegate to the given implementation, unless
// overwritten.
func NewMockgenWorldOsFileFrom(i internal.WorldOsFile) *MockgenWorldOsFile {
	return &MockgenWorldOsFile{
		CloseFunc: &genWorldOsFileCloseFunc{
			defaultHook: i.Close,
		},
		NameFunc: &genWorldOsFileNameFunc{
			defaultHook: i.Name,
		},
		WriteFunc: &genWorldOsFileWriteFunc{
			defaultHook: i.Write,
		},
	}
}

// genWorldOsFileCloseFunc describes the behavior when the Close method of
// the parent MockgenWorldOsFile instance is invoked.
type genWorldOsFileCloseFunc struct {
	defaultHook func() error
	hooks       []func() error
	history     []genWorldOsFileCloseFuncCall
	mutex       sync.Mutex
}

// Close delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockgenWorldOsFile) Close() error {
	r0 := m.CloseFunc.nextHook()()
	m.CloseFunc.appendCall(genWorldOsFileCloseFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Close method of the
// parent MockgenWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *genWorldOsFileCloseFunc) SetDefaultHook(hook func() error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Close method of the parent MockgenWorldOsFile instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldOsFileCloseFunc) PushHook(hook func() error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsFileCloseFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func() error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsFileCloseFunc) PushReturn(r0 error) {
	f.PushHook(func() error {
		return r0
	})
}

func (f *genWorldOsFileCloseFunc) nextHook() func() error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsFileCloseFunc) appendCall(r0 genWorldOsFileCloseFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsFileCloseFuncCall objects
// describing the invocations of this function.
func (f *genWorldOsFileCloseFunc) History() []genWorldOsFileCloseFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsFileCloseFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsFileCloseFuncCall is an object that describes an invocation of
// method Close on an instance of MockgenWorldOsFile.
type genWorldOsFileCloseFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsFileCloseFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsFileCloseFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// genWorldOsFileNameFunc describes the behavior when the Name method of the
// parent MockgenWorldOsFile instance is invoked.
type genWorldOsFileNameFunc struct {
	defaultHook func() string
	hooks       []func() string
	history     []genWorldOsFileNameFuncCall
	mutex       sync.Mutex
}

// Name delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockgenWorldOsFile) Name() string {
	r0 := m.NameFunc.nextHook()()
	m.NameFunc.appendCall(genWorldOsFileNameFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Name method of the
// parent MockgenWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *genWorldOsFileNameFunc) SetDefaultHook(hook func() string) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Name method of the parent MockgenWorldOsFile instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldOsFileNameFunc) PushHook(hook func() string) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsFileNameFunc) SetDefaultReturn(r0 string) {
	f.SetDefaultHook(func() string {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsFileNameFunc) PushReturn(r0 string) {
	f.PushHook(func() string {
		return r0
	})
}

func (f *genWorldOsFileNameFunc) nextHook() func() string {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsFileNameFunc) appendCall(r0 genWorldOsFileNameFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsFileNameFuncCall objects
// describing the invocations of this function.
func (f *genWorldOsFileNameFunc) History() []genWorldOsFileNameFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsFileNameFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsFileNameFuncCall is an object that describes an invocation of
// method Name on an instance of MockgenWorldOsFile.
type genWorldOsFileNameFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 string
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsFileNameFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsFileNameFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// genWorldOsFileWriteFunc describes the behavior when the Write method of
// the parent MockgenWorldOsFile instance is invoked.
type genWorldOsFileWriteFunc struct {
	defaultHook func([]byte) (int, error)
	hooks       []func([]byte) (int, error)
	history     []genWorldOsFileWriteFuncCall
	mutex       sync.Mutex
}

// Write delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockgenWorldOsFile) Write(v0 []byte) (int, error) {
	r0, r1 := m.WriteFunc.nextHook()(v0)
	m.WriteFunc.appendCall(genWorldOsFileWriteFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the Write method of the
// parent MockgenWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *genWorldOsFileWriteFunc) SetDefaultHook(hook func([]byte) (int, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Write method of the parent MockgenWorldOsFile instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *genWorldOsFileWriteFunc) PushHook(hook func([]byte) (int, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *genWorldOsFileWriteFunc) SetDefaultReturn(r0 int, r1 error) {
	f.SetDefaultHook(func([]byte) (int, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *genWorldOsFileWriteFunc) PushReturn(r0 int, r1 error) {
	f.PushHook(func([]byte) (int, error) {
		return r0, r1
	})
}

func (f *genWorldOsFileWriteFunc) nextHook() func([]byte) (int, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *genWorldOsFileWriteFunc) appendCall(r0 genWorldOsFileWriteFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of genWorldOsFileWriteFuncCall objects
// describing the invocations of this function.
func (f *genWorldOsFileWriteFunc) History() []genWorldOsFileWriteFuncCall {
	f.mutex.Lock()
	history := make([]genWorldOsFileWriteFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// genWorldOsFileWriteFuncCall is an object that describes an invocation of
// method Write on an instance of MockgenWorldOsFile.
type genWorldOsFileWriteFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 []byte
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 int
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c genWorldOsFileWriteFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c genWorldOsFileWriteFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}
