// Code generated by go-mockgen 2.1.1; DO NOT EDIT.

package internal_test

import (
	"sync"

	worldcmds "github.com/powerman/ebpf-same-cgroup-mark/test/internal/worldcmds"
)

// MockStubWorldCmds is a mock implementation of the WorldCmds interface
// (from the package
// github.com/powerman/ebpf-same-cgroup-mark/test/internal/worldcmds) used
// for unit testing.
type MockStubWorldCmds struct {
	// BpftoolCgroupAttachFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupAttach.
	BpftoolCgroupAttachFunc *StubWorldCmdsBpftoolCgroupAttachFunc
	// BpftoolCgroupDetachFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupDetach.
	BpftoolCgroupDetachFunc *StubWorldCmdsBpftoolCgroupDetachFunc
	// BpftoolCgroupShowFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolCgroupShow.
	BpftoolCgroupShowFunc *StubWorldCmdsBpftoolCgroupShowFunc
	// BpftoolMapUpdateFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolMapUpdate.
	BpftoolMapUpdateFunc *StubWorldCmdsBpftoolMapUpdateFunc
	// BpftoolProgLoadAllFunc is an instance of a mock function object
	// controlling the behavior of the method BpftoolProgLoadAll.
	BpftoolProgLoadAllFunc *StubWorldCmdsBpftoolProgLoadAllFunc
	// MountBPFFunc is an instance of a mock function object controlling the
	// behavior of the method MountBPF.
	MountBPFFunc *StubWorldCmdsMountBPFFunc
	// MountpointFunc is an instance of a mock function object controlling
	// the behavior of the method Mountpoint.
	MountpointFunc *StubWorldCmdsMountpointFunc
}

// NewMockStubWorldCmds creates a new mock of the WorldCmds interface. All
// methods return zero values for all results, unless overwritten.
func NewMockStubWorldCmds() *MockStubWorldCmds {
	return &MockStubWorldCmds{
		BpftoolCgroupAttachFunc: &StubWorldCmdsBpftoolCgroupAttachFunc{
			defaultHook: func(string, string, string) (r0 error) {
				return
			},
		},
		BpftoolCgroupDetachFunc: &StubWorldCmdsBpftoolCgroupDetachFunc{
			defaultHook: func(string, string, string) (r0 error) {
				return
			},
		},
		BpftoolCgroupShowFunc: &StubWorldCmdsBpftoolCgroupShowFunc{
			defaultHook: func(string) (r0 []byte, r1 error) {
				return
			},
		},
		BpftoolMapUpdateFunc: &StubWorldCmdsBpftoolMapUpdateFunc{
			defaultHook: func(...string) (r0 error) {
				return
			},
		},
		BpftoolProgLoadAllFunc: &StubWorldCmdsBpftoolProgLoadAllFunc{
			defaultHook: func(string, string, string) (r0 []byte, r1 error) {
				return
			},
		},
		MountBPFFunc: &StubWorldCmdsMountBPFFunc{
			defaultHook: func(string, string) (r0 []byte, r1 error) {
				return
			},
		},
		MountpointFunc: &StubWorldCmdsMountpointFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
	}
}

// NewStrictMockStubWorldCmds creates a new mock of the WorldCmds interface.
// All methods panic on invocation, unless overwritten.
func NewStrictMockStubWorldCmds() *MockStubWorldCmds {
	return &MockStubWorldCmds{
		BpftoolCgroupAttachFunc: &StubWorldCmdsBpftoolCgroupAttachFunc{
			defaultHook: func(string, string, string) error {
				panic("unexpected invocation of MockStubWorldCmds.BpftoolCgroupAttach")
			},
		},
		BpftoolCgroupDetachFunc: &StubWorldCmdsBpftoolCgroupDetachFunc{
			defaultHook: func(string, string, string) error {
				panic("unexpected invocation of MockStubWorldCmds.BpftoolCgroupDetach")
			},
		},
		BpftoolCgroupShowFunc: &StubWorldCmdsBpftoolCgroupShowFunc{
			defaultHook: func(string) ([]byte, error) {
				panic("unexpected invocation of MockStubWorldCmds.BpftoolCgroupShow")
			},
		},
		BpftoolMapUpdateFunc: &StubWorldCmdsBpftoolMapUpdateFunc{
			defaultHook: func(...string) error {
				panic("unexpected invocation of MockStubWorldCmds.BpftoolMapUpdate")
			},
		},
		BpftoolProgLoadAllFunc: &StubWorldCmdsBpftoolProgLoadAllFunc{
			defaultHook: func(string, string, string) ([]byte, error) {
				panic("unexpected invocation of MockStubWorldCmds.BpftoolProgLoadAll")
			},
		},
		MountBPFFunc: &StubWorldCmdsMountBPFFunc{
			defaultHook: func(string, string) ([]byte, error) {
				panic("unexpected invocation of MockStubWorldCmds.MountBPF")
			},
		},
		MountpointFunc: &StubWorldCmdsMountpointFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockStubWorldCmds.Mountpoint")
			},
		},
	}
}

// NewMockStubWorldCmdsFrom creates a new mock of the MockStubWorldCmds
// interface. All methods delegate to the given implementation, unless
// overwritten.
func NewMockStubWorldCmdsFrom(i worldcmds.WorldCmds) *MockStubWorldCmds {
	return &MockStubWorldCmds{
		BpftoolCgroupAttachFunc: &StubWorldCmdsBpftoolCgroupAttachFunc{
			defaultHook: i.BpftoolCgroupAttach,
		},
		BpftoolCgroupDetachFunc: &StubWorldCmdsBpftoolCgroupDetachFunc{
			defaultHook: i.BpftoolCgroupDetach,
		},
		BpftoolCgroupShowFunc: &StubWorldCmdsBpftoolCgroupShowFunc{
			defaultHook: i.BpftoolCgroupShow,
		},
		BpftoolMapUpdateFunc: &StubWorldCmdsBpftoolMapUpdateFunc{
			defaultHook: i.BpftoolMapUpdate,
		},
		BpftoolProgLoadAllFunc: &StubWorldCmdsBpftoolProgLoadAllFunc{
			defaultHook: i.BpftoolProgLoadAll,
		},
		MountBPFFunc: &StubWorldCmdsMountBPFFunc{
			defaultHook: i.MountBPF,
		},
		MountpointFunc: &StubWorldCmdsMountpointFunc{
			defaultHook: i.Mountpoint,
		},
	}
}

// StubWorldCmdsBpftoolCgroupAttachFunc describes the behavior when the
// BpftoolCgroupAttach method of the parent MockStubWorldCmds instance is
// invoked.
type StubWorldCmdsBpftoolCgroupAttachFunc struct {
	defaultHook func(string, string, string) error
	hooks       []func(string, string, string) error
	history     []StubWorldCmdsBpftoolCgroupAttachFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupAttach delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorldCmds) BpftoolCgroupAttach(v0 string, v1 string, v2 string) error {
	r0 := m.BpftoolCgroupAttachFunc.nextHook()(v0, v1, v2)
	m.BpftoolCgroupAttachFunc.appendCall(StubWorldCmdsBpftoolCgroupAttachFuncCall{v0, v1, v2, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolCgroupAttach
// method of the parent MockStubWorldCmds instance is invoked and the hook
// queue is empty.
func (f *StubWorldCmdsBpftoolCgroupAttachFunc) SetDefaultHook(hook func(string, string, string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupAttach method of the parent MockStubWorldCmds instance
// invokes the hook at the front of the queue and discards it. After the
// queue is empty, the default hook function is invoked for any future
// action.
func (f *StubWorldCmdsBpftoolCgroupAttachFunc) PushHook(hook func(string, string, string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldCmdsBpftoolCgroupAttachFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, string, string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldCmdsBpftoolCgroupAttachFunc) PushReturn(r0 error) {
	f.PushHook(func(string, string, string) error {
		return r0
	})
}

func (f *StubWorldCmdsBpftoolCgroupAttachFunc) nextHook() func(string, string, string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldCmdsBpftoolCgroupAttachFunc) appendCall(r0 StubWorldCmdsBpftoolCgroupAttachFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldCmdsBpftoolCgroupAttachFuncCall
// objects describing the invocations of this function.
func (f *StubWorldCmdsBpftoolCgroupAttachFunc) History() []StubWorldCmdsBpftoolCgroupAttachFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldCmdsBpftoolCgroupAttachFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldCmdsBpftoolCgroupAttachFuncCall is an object that describes an
// invocation of method BpftoolCgroupAttach on an instance of
// MockStubWorldCmds.
type StubWorldCmdsBpftoolCgroupAttachFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldCmdsBpftoolCgroupAttachFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldCmdsBpftoolCgroupAttachFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldCmdsBpftoolCgroupDetachFunc describes the behavior when the
// BpftoolCgroupDetach method of the parent MockStubWorldCmds instance is
// invoked.
type StubWorldCmdsBpftoolCgroupDetachFunc struct {
	defaultHook func(string, string, string) error
	hooks       []func(string, string, string) error
	history     []StubWorldCmdsBpftoolCgroupDetachFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupDetach delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorldCmds) BpftoolCgroupDetach(v0 string, v1 string, v2 string) error {
	r0 := m.BpftoolCgroupDetachFunc.nextHook()(v0, v1, v2)
	m.BpftoolCgroupDetachFunc.appendCall(StubWorldCmdsBpftoolCgroupDetachFuncCall{v0, v1, v2, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolCgroupDetach
// method of the parent MockStubWorldCmds instance is invoked and the hook
// queue is empty.
func (f *StubWorldCmdsBpftoolCgroupDetachFunc) SetDefaultHook(hook func(string, string, string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupDetach method of the parent MockStubWorldCmds instance
// invokes the hook at the front of the queue and discards it. After the
// queue is empty, the default hook function is invoked for any future
// action.
func (f *StubWorldCmdsBpftoolCgroupDetachFunc) PushHook(hook func(string, string, string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldCmdsBpftoolCgroupDetachFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, string, string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldCmdsBpftoolCgroupDetachFunc) PushReturn(r0 error) {
	f.PushHook(func(string, string, string) error {
		return r0
	})
}

func (f *StubWorldCmdsBpftoolCgroupDetachFunc) nextHook() func(string, string, string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldCmdsBpftoolCgroupDetachFunc) appendCall(r0 StubWorldCmdsBpftoolCgroupDetachFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldCmdsBpftoolCgroupDetachFuncCall
// objects describing the invocations of this function.
func (f *StubWorldCmdsBpftoolCgroupDetachFunc) History() []StubWorldCmdsBpftoolCgroupDetachFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldCmdsBpftoolCgroupDetachFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldCmdsBpftoolCgroupDetachFuncCall is an object that describes an
// invocation of method BpftoolCgroupDetach on an instance of
// MockStubWorldCmds.
type StubWorldCmdsBpftoolCgroupDetachFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldCmdsBpftoolCgroupDetachFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldCmdsBpftoolCgroupDetachFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldCmdsBpftoolCgroupShowFunc describes the behavior when the
// BpftoolCgroupShow method of the parent MockStubWorldCmds instance is
// invoked.
type StubWorldCmdsBpftoolCgroupShowFunc struct {
	defaultHook func(string) ([]byte, error)
	hooks       []func(string) ([]byte, error)
	history     []StubWorldCmdsBpftoolCgroupShowFuncCall
	mutex       sync.Mutex
}

// BpftoolCgroupShow delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorldCmds) BpftoolCgroupShow(v0 string) ([]byte, error) {
	r0, r1 := m.BpftoolCgroupShowFunc.nextHook()(v0)
	m.BpftoolCgroupShowFunc.appendCall(StubWorldCmdsBpftoolCgroupShowFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the BpftoolCgroupShow
// method of the parent MockStubWorldCmds instance is invoked and the hook
// queue is empty.
func (f *StubWorldCmdsBpftoolCgroupShowFunc) SetDefaultHook(hook func(string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolCgroupShow method of the parent MockStubWorldCmds instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *StubWorldCmdsBpftoolCgroupShowFunc) PushHook(hook func(string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldCmdsBpftoolCgroupShowFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldCmdsBpftoolCgroupShowFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string) ([]byte, error) {
		return r0, r1
	})
}

func (f *StubWorldCmdsBpftoolCgroupShowFunc) nextHook() func(string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldCmdsBpftoolCgroupShowFunc) appendCall(r0 StubWorldCmdsBpftoolCgroupShowFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldCmdsBpftoolCgroupShowFuncCall
// objects describing the invocations of this function.
func (f *StubWorldCmdsBpftoolCgroupShowFunc) History() []StubWorldCmdsBpftoolCgroupShowFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldCmdsBpftoolCgroupShowFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldCmdsBpftoolCgroupShowFuncCall is an object that describes an
// invocation of method BpftoolCgroupShow on an instance of
// MockStubWorldCmds.
type StubWorldCmdsBpftoolCgroupShowFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldCmdsBpftoolCgroupShowFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldCmdsBpftoolCgroupShowFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldCmdsBpftoolMapUpdateFunc describes the behavior when the
// BpftoolMapUpdate method of the parent MockStubWorldCmds instance is
// invoked.
type StubWorldCmdsBpftoolMapUpdateFunc struct {
	defaultHook func(...string) error
	hooks       []func(...string) error
	history     []StubWorldCmdsBpftoolMapUpdateFuncCall
	mutex       sync.Mutex
}

// BpftoolMapUpdate delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorldCmds) BpftoolMapUpdate(v0 ...string) error {
	r0 := m.BpftoolMapUpdateFunc.nextHook()(v0...)
	m.BpftoolMapUpdateFunc.appendCall(StubWorldCmdsBpftoolMapUpdateFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the BpftoolMapUpdate
// method of the parent MockStubWorldCmds instance is invoked and the hook
// queue is empty.
func (f *StubWorldCmdsBpftoolMapUpdateFunc) SetDefaultHook(hook func(...string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolMapUpdate method of the parent MockStubWorldCmds instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *StubWorldCmdsBpftoolMapUpdateFunc) PushHook(hook func(...string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldCmdsBpftoolMapUpdateFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(...string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldCmdsBpftoolMapUpdateFunc) PushReturn(r0 error) {
	f.PushHook(func(...string) error {
		return r0
	})
}

func (f *StubWorldCmdsBpftoolMapUpdateFunc) nextHook() func(...string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldCmdsBpftoolMapUpdateFunc) appendCall(r0 StubWorldCmdsBpftoolMapUpdateFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldCmdsBpftoolMapUpdateFuncCall
// objects describing the invocations of this function.
func (f *StubWorldCmdsBpftoolMapUpdateFunc) History() []StubWorldCmdsBpftoolMapUpdateFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldCmdsBpftoolMapUpdateFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldCmdsBpftoolMapUpdateFuncCall is an object that describes an
// invocation of method BpftoolMapUpdate on an instance of
// MockStubWorldCmds.
type StubWorldCmdsBpftoolMapUpdateFuncCall struct {
	// Arg0 is a slice containing the values of the variadic arguments
	// passed to this method invocation.
	Arg0 []string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation. The variadic slice argument is flattened in this array such
// that one positional argument and three variadic arguments would result in
// a slice of four, not two.
func (c StubWorldCmdsBpftoolMapUpdateFuncCall) Args() []interface{} {
	trailing := []interface{}{}
	for _, val := range c.Arg0 {
		trailing = append(trailing, val)
	}

	return append([]interface{}{}, trailing...)
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldCmdsBpftoolMapUpdateFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldCmdsBpftoolProgLoadAllFunc describes the behavior when the
// BpftoolProgLoadAll method of the parent MockStubWorldCmds instance is
// invoked.
type StubWorldCmdsBpftoolProgLoadAllFunc struct {
	defaultHook func(string, string, string) ([]byte, error)
	hooks       []func(string, string, string) ([]byte, error)
	history     []StubWorldCmdsBpftoolProgLoadAllFuncCall
	mutex       sync.Mutex
}

// BpftoolProgLoadAll delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorldCmds) BpftoolProgLoadAll(v0 string, v1 string, v2 string) ([]byte, error) {
	r0, r1 := m.BpftoolProgLoadAllFunc.nextHook()(v0, v1, v2)
	m.BpftoolProgLoadAllFunc.appendCall(StubWorldCmdsBpftoolProgLoadAllFuncCall{v0, v1, v2, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the BpftoolProgLoadAll
// method of the parent MockStubWorldCmds instance is invoked and the hook
// queue is empty.
func (f *StubWorldCmdsBpftoolProgLoadAllFunc) SetDefaultHook(hook func(string, string, string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// BpftoolProgLoadAll method of the parent MockStubWorldCmds instance
// invokes the hook at the front of the queue and discards it. After the
// queue is empty, the default hook function is invoked for any future
// action.
func (f *StubWorldCmdsBpftoolProgLoadAllFunc) PushHook(hook func(string, string, string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldCmdsBpftoolProgLoadAllFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string, string, string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldCmdsBpftoolProgLoadAllFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string, string, string) ([]byte, error) {
		return r0, r1
	})
}

func (f *StubWorldCmdsBpftoolProgLoadAllFunc) nextHook() func(string, string, string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldCmdsBpftoolProgLoadAllFunc) appendCall(r0 StubWorldCmdsBpftoolProgLoadAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldCmdsBpftoolProgLoadAllFuncCall
// objects describing the invocations of this function.
func (f *StubWorldCmdsBpftoolProgLoadAllFunc) History() []StubWorldCmdsBpftoolProgLoadAllFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldCmdsBpftoolProgLoadAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldCmdsBpftoolProgLoadAllFuncCall is an object that describes an
// invocation of method BpftoolProgLoadAll on an instance of
// MockStubWorldCmds.
type StubWorldCmdsBpftoolProgLoadAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Arg2 is the value of the 3rd argument passed to this method
	// invocation.
	Arg2 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldCmdsBpftoolProgLoadAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1, c.Arg2}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldCmdsBpftoolProgLoadAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldCmdsMountBPFFunc describes the behavior when the MountBPF method
// of the parent MockStubWorldCmds instance is invoked.
type StubWorldCmdsMountBPFFunc struct {
	defaultHook func(string, string) ([]byte, error)
	hooks       []func(string, string) ([]byte, error)
	history     []StubWorldCmdsMountBPFFuncCall
	mutex       sync.Mutex
}

// MountBPF delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldCmds) MountBPF(v0 string, v1 string) ([]byte, error) {
	r0, r1 := m.MountBPFFunc.nextHook()(v0, v1)
	m.MountBPFFunc.appendCall(StubWorldCmdsMountBPFFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the MountBPF method of
// the parent MockStubWorldCmds instance is invoked and the hook queue is
// empty.
func (f *StubWorldCmdsMountBPFFunc) SetDefaultHook(hook func(string, string) ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// MountBPF method of the parent MockStubWorldCmds instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldCmdsMountBPFFunc) PushHook(hook func(string, string) ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldCmdsMountBPFFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func(string, string) ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldCmdsMountBPFFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func(string, string) ([]byte, error) {
		return r0, r1
	})
}

func (f *StubWorldCmdsMountBPFFunc) nextHook() func(string, string) ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldCmdsMountBPFFunc) appendCall(r0 StubWorldCmdsMountBPFFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldCmdsMountBPFFuncCall objects
// describing the invocations of this function.
func (f *StubWorldCmdsMountBPFFunc) History() []StubWorldCmdsMountBPFFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldCmdsMountBPFFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldCmdsMountBPFFuncCall is an object that describes an invocation
// of method MountBPF on an instance of MockStubWorldCmds.
type StubWorldCmdsMountBPFFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldCmdsMountBPFFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldCmdsMountBPFFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldCmdsMountpointFunc describes the behavior when the Mountpoint
// method of the parent MockStubWorldCmds instance is invoked.
type StubWorldCmdsMountpointFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []StubWorldCmdsMountpointFuncCall
	mutex       sync.Mutex
}

// Mountpoint delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorldCmds) Mountpoint(v0 string) error {
	r0 := m.MountpointFunc.nextHook()(v0)
	m.MountpointFunc.appendCall(StubWorldCmdsMountpointFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the Mountpoint method of
// the parent MockStubWorldCmds instance is invoked and the hook queue is
// empty.
func (f *StubWorldCmdsMountpointFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Mountpoint method of the parent MockStubWorldCmds instance invokes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *StubWorldCmdsMountpointFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldCmdsMountpointFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldCmdsMountpointFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *StubWorldCmdsMountpointFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldCmdsMountpointFunc) appendCall(r0 StubWorldCmdsMountpointFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldCmdsMountpointFuncCall objects
// describing the invocations of this function.
func (f *StubWorldCmdsMountpointFunc) History() []StubWorldCmdsMountpointFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldCmdsMountpointFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldCmdsMountpointFuncCall is an object that describes an invocation
// of method Mountpoint on an instance of MockStubWorldCmds.
type StubWorldCmdsMountpointFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldCmdsMountpointFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldCmdsMountpointFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}
