// Code generated by go-mockgen 2.1.1; DO NOT EDIT.

package internal_test

import (
	"io/fs"
	"sync"

	internal "github.com/powerman/ebpf-same-cgroup-mark/internal"
)

// MockStubWorld is a mock implementation of the World interface (from the
// package github.com/powerman/ebpf-same-cgroup-mark/internal) used for unit
// testing.
type MockStubWorld struct {
	// ExecCommandFunc is an instance of a mock function object controlling
	// the behavior of the method ExecCommand.
	ExecCommandFunc *StubWorldExecCommandFunc
	// OsCreateTempFunc is an instance of a mock function object controlling
	// the behavior of the method OsCreateTemp.
	OsCreateTempFunc *StubWorldOsCreateTempFunc
	// OsGeteuidFunc is an instance of a mock function object controlling
	// the behavior of the method OsGeteuid.
	OsGeteuidFunc *StubWorldOsGeteuidFunc
	// OsMkdirAllFunc is an instance of a mock function object controlling
	// the behavior of the method OsMkdirAll.
	OsMkdirAllFunc *StubWorldOsMkdirAllFunc
	// OsRemoveFunc is an instance of a mock function object controlling the
	// behavior of the method OsRemove.
	OsRemoveFunc *StubWorldOsRemoveFunc
	// OsRemoveAllFunc is an instance of a mock function object controlling
	// the behavior of the method OsRemoveAll.
	OsRemoveAllFunc *StubWorldOsRemoveAllFunc
	// OsStatFunc is an instance of a mock function object controlling the
	// behavior of the method OsStat.
	OsStatFunc *StubWorldOsStatFunc
}

// NewMockStubWorld creates a new mock of the World interface. All methods
// return zero values for all results, unless overwritten.
func NewMockStubWorld() *MockStubWorld {
	return &MockStubWorld{
		ExecCommandFunc: &StubWorldExecCommandFunc{
			defaultHook: func(string, ...string) (r0 internal.WorldExecCmd) {
				return
			},
		},
		OsCreateTempFunc: &StubWorldOsCreateTempFunc{
			defaultHook: func(string, string) (r0 internal.WorldOsFile, r1 error) {
				return
			},
		},
		OsGeteuidFunc: &StubWorldOsGeteuidFunc{
			defaultHook: func() (r0 int) {
				return
			},
		},
		OsMkdirAllFunc: &StubWorldOsMkdirAllFunc{
			defaultHook: func(string, fs.FileMode) (r0 error) {
				return
			},
		},
		OsRemoveFunc: &StubWorldOsRemoveFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
		OsRemoveAllFunc: &StubWorldOsRemoveAllFunc{
			defaultHook: func(string) (r0 error) {
				return
			},
		},
		OsStatFunc: &StubWorldOsStatFunc{
			defaultHook: func(string) (r0 fs.FileInfo, r1 error) {
				return
			},
		},
	}
}

// NewStrictMockStubWorld creates a new mock of the World interface. All
// methods panic on invocation, unless overwritten.
func NewStrictMockStubWorld() *MockStubWorld {
	return &MockStubWorld{
		ExecCommandFunc: &StubWorldExecCommandFunc{
			defaultHook: func(string, ...string) internal.WorldExecCmd {
				panic("unexpected invocation of MockStubWorld.ExecCommand")
			},
		},
		OsCreateTempFunc: &StubWorldOsCreateTempFunc{
			defaultHook: func(string, string) (internal.WorldOsFile, error) {
				panic("unexpected invocation of MockStubWorld.OsCreateTemp")
			},
		},
		OsGeteuidFunc: &StubWorldOsGeteuidFunc{
			defaultHook: func() int {
				panic("unexpected invocation of MockStubWorld.OsGeteuid")
			},
		},
		OsMkdirAllFunc: &StubWorldOsMkdirAllFunc{
			defaultHook: func(string, fs.FileMode) error {
				panic("unexpected invocation of MockStubWorld.OsMkdirAll")
			},
		},
		OsRemoveFunc: &StubWorldOsRemoveFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockStubWorld.OsRemove")
			},
		},
		OsRemoveAllFunc: &StubWorldOsRemoveAllFunc{
			defaultHook: func(string) error {
				panic("unexpected invocation of MockStubWorld.OsRemoveAll")
			},
		},
		OsStatFunc: &StubWorldOsStatFunc{
			defaultHook: func(string) (fs.FileInfo, error) {
				panic("unexpected invocation of MockStubWorld.OsStat")
			},
		},
	}
}

// NewMockStubWorldFrom creates a new mock of the MockStubWorld interface.
// All methods delegate to the given implementation, unless overwritten.
func NewMockStubWorldFrom(i internal.World) *MockStubWorld {
	return &MockStubWorld{
		ExecCommandFunc: &StubWorldExecCommandFunc{
			defaultHook: i.ExecCommand,
		},
		OsCreateTempFunc: &StubWorldOsCreateTempFunc{
			defaultHook: i.OsCreateTemp,
		},
		OsGeteuidFunc: &StubWorldOsGeteuidFunc{
			defaultHook: i.OsGeteuid,
		},
		OsMkdirAllFunc: &StubWorldOsMkdirAllFunc{
			defaultHook: i.OsMkdirAll,
		},
		OsRemoveFunc: &StubWorldOsRemoveFunc{
			defaultHook: i.OsRemove,
		},
		OsRemoveAllFunc: &StubWorldOsRemoveAllFunc{
			defaultHook: i.OsRemoveAll,
		},
		OsStatFunc: &StubWorldOsStatFunc{
			defaultHook: i.OsStat,
		},
	}
}

// StubWorldExecCommandFunc describes the behavior when the ExecCommand
// method of the parent MockStubWorld instance is invoked.
type StubWorldExecCommandFunc struct {
	defaultHook func(string, ...string) internal.WorldExecCmd
	hooks       []func(string, ...string) internal.WorldExecCmd
	history     []StubWorldExecCommandFuncCall
	mutex       sync.Mutex
}

// ExecCommand delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorld) ExecCommand(v0 string, v1 ...string) internal.WorldExecCmd {
	r0 := m.ExecCommandFunc.nextHook()(v0, v1...)
	m.ExecCommandFunc.appendCall(StubWorldExecCommandFuncCall{v0, v1, r0})
	return r0
}

// SetDefaultHook sets function that is called when the ExecCommand method
// of the parent MockStubWorld instance is invoked and the hook queue is
// empty.
func (f *StubWorldExecCommandFunc) SetDefaultHook(hook func(string, ...string) internal.WorldExecCmd) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// ExecCommand method of the parent MockStubWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldExecCommandFunc) PushHook(hook func(string, ...string) internal.WorldExecCmd) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldExecCommandFunc) SetDefaultReturn(r0 internal.WorldExecCmd) {
	f.SetDefaultHook(func(string, ...string) internal.WorldExecCmd {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldExecCommandFunc) PushReturn(r0 internal.WorldExecCmd) {
	f.PushHook(func(string, ...string) internal.WorldExecCmd {
		return r0
	})
}

func (f *StubWorldExecCommandFunc) nextHook() func(string, ...string) internal.WorldExecCmd {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldExecCommandFunc) appendCall(r0 StubWorldExecCommandFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldExecCommandFuncCall objects
// describing the invocations of this function.
func (f *StubWorldExecCommandFunc) History() []StubWorldExecCommandFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldExecCommandFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldExecCommandFuncCall is an object that describes an invocation of
// method ExecCommand on an instance of MockStubWorld.
type StubWorldExecCommandFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is a slice containing the values of the variadic arguments
	// passed to this method invocation.
	Arg1 []string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 internal.WorldExecCmd
}

// Args returns an interface slice containing the arguments of this
// invocation. The variadic slice argument is flattened in this array such
// that one positional argument and three variadic arguments would result in
// a slice of four, not two.
func (c StubWorldExecCommandFuncCall) Args() []interface{} {
	trailing := []interface{}{}
	for _, val := range c.Arg1 {
		trailing = append(trailing, val)
	}

	return append([]interface{}{c.Arg0}, trailing...)
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldExecCommandFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsCreateTempFunc describes the behavior when the OsCreateTemp
// method of the parent MockStubWorld instance is invoked.
type StubWorldOsCreateTempFunc struct {
	defaultHook func(string, string) (internal.WorldOsFile, error)
	hooks       []func(string, string) (internal.WorldOsFile, error)
	history     []StubWorldOsCreateTempFuncCall
	mutex       sync.Mutex
}

// OsCreateTemp delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorld) OsCreateTemp(v0 string, v1 string) (internal.WorldOsFile, error) {
	r0, r1 := m.OsCreateTempFunc.nextHook()(v0, v1)
	m.OsCreateTempFunc.appendCall(StubWorldOsCreateTempFuncCall{v0, v1, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the OsCreateTemp method
// of the parent MockStubWorld instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsCreateTempFunc) SetDefaultHook(hook func(string, string) (internal.WorldOsFile, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsCreateTemp method of the parent MockStubWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsCreateTempFunc) PushHook(hook func(string, string) (internal.WorldOsFile, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsCreateTempFunc) SetDefaultReturn(r0 internal.WorldOsFile, r1 error) {
	f.SetDefaultHook(func(string, string) (internal.WorldOsFile, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsCreateTempFunc) PushReturn(r0 internal.WorldOsFile, r1 error) {
	f.PushHook(func(string, string) (internal.WorldOsFile, error) {
		return r0, r1
	})
}

func (f *StubWorldOsCreateTempFunc) nextHook() func(string, string) (internal.WorldOsFile, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsCreateTempFunc) appendCall(r0 StubWorldOsCreateTempFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsCreateTempFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsCreateTempFunc) History() []StubWorldOsCreateTempFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsCreateTempFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsCreateTempFuncCall is an object that describes an invocation
// of method OsCreateTemp on an instance of MockStubWorld.
type StubWorldOsCreateTempFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 internal.WorldOsFile
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsCreateTempFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsCreateTempFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldOsGeteuidFunc describes the behavior when the OsGeteuid method
// of the parent MockStubWorld instance is invoked.
type StubWorldOsGeteuidFunc struct {
	defaultHook func() int
	hooks       []func() int
	history     []StubWorldOsGeteuidFuncCall
	mutex       sync.Mutex
}

// OsGeteuid delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorld) OsGeteuid() int {
	r0 := m.OsGeteuidFunc.nextHook()()
	m.OsGeteuidFunc.appendCall(StubWorldOsGeteuidFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsGeteuid method of
// the parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldOsGeteuidFunc) SetDefaultHook(hook func() int) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsGeteuid method of the parent MockStubWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsGeteuidFunc) PushHook(hook func() int) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsGeteuidFunc) SetDefaultReturn(r0 int) {
	f.SetDefaultHook(func() int {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsGeteuidFunc) PushReturn(r0 int) {
	f.PushHook(func() int {
		return r0
	})
}

func (f *StubWorldOsGeteuidFunc) nextHook() func() int {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsGeteuidFunc) appendCall(r0 StubWorldOsGeteuidFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsGeteuidFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsGeteuidFunc) History() []StubWorldOsGeteuidFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsGeteuidFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsGeteuidFuncCall is an object that describes an invocation of
// method OsGeteuid on an instance of MockStubWorld.
type StubWorldOsGeteuidFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 int
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsGeteuidFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsGeteuidFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsMkdirAllFunc describes the behavior when the OsMkdirAll method
// of the parent MockStubWorld instance is invoked.
type StubWorldOsMkdirAllFunc struct {
	defaultHook func(string, fs.FileMode) error
	hooks       []func(string, fs.FileMode) error
	history     []StubWorldOsMkdirAllFuncCall
	mutex       sync.Mutex
}

// OsMkdirAll delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorld) OsMkdirAll(v0 string, v1 fs.FileMode) error {
	r0 := m.OsMkdirAllFunc.nextHook()(v0, v1)
	m.OsMkdirAllFunc.appendCall(StubWorldOsMkdirAllFuncCall{v0, v1, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsMkdirAll method of
// the parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldOsMkdirAllFunc) SetDefaultHook(hook func(string, fs.FileMode) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsMkdirAll method of the parent MockStubWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsMkdirAllFunc) PushHook(hook func(string, fs.FileMode) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsMkdirAllFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string, fs.FileMode) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsMkdirAllFunc) PushReturn(r0 error) {
	f.PushHook(func(string, fs.FileMode) error {
		return r0
	})
}

func (f *StubWorldOsMkdirAllFunc) nextHook() func(string, fs.FileMode) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsMkdirAllFunc) appendCall(r0 StubWorldOsMkdirAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsMkdirAllFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsMkdirAllFunc) History() []StubWorldOsMkdirAllFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsMkdirAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsMkdirAllFuncCall is an object that describes an invocation of
// method OsMkdirAll on an instance of MockStubWorld.
type StubWorldOsMkdirAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Arg1 is the value of the 2nd argument passed to this method
	// invocation.
	Arg1 fs.FileMode
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsMkdirAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0, c.Arg1}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsMkdirAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsRemoveFunc describes the behavior when the OsRemove method of
// the parent MockStubWorld instance is invoked.
type StubWorldOsRemoveFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []StubWorldOsRemoveFuncCall
	mutex       sync.Mutex
}

// OsRemove delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorld) OsRemove(v0 string) error {
	r0 := m.OsRemoveFunc.nextHook()(v0)
	m.OsRemoveFunc.appendCall(StubWorldOsRemoveFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsRemove method of
// the parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldOsRemoveFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsRemove method of the parent MockStubWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsRemoveFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsRemoveFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsRemoveFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *StubWorldOsRemoveFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsRemoveFunc) appendCall(r0 StubWorldOsRemoveFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsRemoveFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsRemoveFunc) History() []StubWorldOsRemoveFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsRemoveFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsRemoveFuncCall is an object that describes an invocation of
// method OsRemove on an instance of MockStubWorld.
type StubWorldOsRemoveFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsRemoveFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsRemoveFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsRemoveAllFunc describes the behavior when the OsRemoveAll
// method of the parent MockStubWorld instance is invoked.
type StubWorldOsRemoveAllFunc struct {
	defaultHook func(string) error
	hooks       []func(string) error
	history     []StubWorldOsRemoveAllFuncCall
	mutex       sync.Mutex
}

// OsRemoveAll delegates to the next hook function in the queue and stores
// the parameter and result values of this invocation.
func (m *MockStubWorld) OsRemoveAll(v0 string) error {
	r0 := m.OsRemoveAllFunc.nextHook()(v0)
	m.OsRemoveAllFunc.appendCall(StubWorldOsRemoveAllFuncCall{v0, r0})
	return r0
}

// SetDefaultHook sets function that is called when the OsRemoveAll method
// of the parent MockStubWorld instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsRemoveAllFunc) SetDefaultHook(hook func(string) error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsRemoveAll method of the parent MockStubWorld instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsRemoveAllFunc) PushHook(hook func(string) error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsRemoveAllFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func(string) error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsRemoveAllFunc) PushReturn(r0 error) {
	f.PushHook(func(string) error {
		return r0
	})
}

func (f *StubWorldOsRemoveAllFunc) nextHook() func(string) error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsRemoveAllFunc) appendCall(r0 StubWorldOsRemoveAllFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsRemoveAllFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsRemoveAllFunc) History() []StubWorldOsRemoveAllFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsRemoveAllFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsRemoveAllFuncCall is an object that describes an invocation of
// method OsRemoveAll on an instance of MockStubWorld.
type StubWorldOsRemoveAllFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsRemoveAllFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsRemoveAllFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsStatFunc describes the behavior when the OsStat method of the
// parent MockStubWorld instance is invoked.
type StubWorldOsStatFunc struct {
	defaultHook func(string) (fs.FileInfo, error)
	hooks       []func(string) (fs.FileInfo, error)
	history     []StubWorldOsStatFuncCall
	mutex       sync.Mutex
}

// OsStat delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorld) OsStat(v0 string) (fs.FileInfo, error) {
	r0, r1 := m.OsStatFunc.nextHook()(v0)
	m.OsStatFunc.appendCall(StubWorldOsStatFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the OsStat method of the
// parent MockStubWorld instance is invoked and the hook queue is empty.
func (f *StubWorldOsStatFunc) SetDefaultHook(hook func(string) (fs.FileInfo, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// OsStat method of the parent MockStubWorld instance invokes the hook at
// the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsStatFunc) PushHook(hook func(string) (fs.FileInfo, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsStatFunc) SetDefaultReturn(r0 fs.FileInfo, r1 error) {
	f.SetDefaultHook(func(string) (fs.FileInfo, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsStatFunc) PushReturn(r0 fs.FileInfo, r1 error) {
	f.PushHook(func(string) (fs.FileInfo, error) {
		return r0, r1
	})
}

func (f *StubWorldOsStatFunc) nextHook() func(string) (fs.FileInfo, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsStatFunc) appendCall(r0 StubWorldOsStatFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsStatFuncCall objects describing
// the invocations of this function.
func (f *StubWorldOsStatFunc) History() []StubWorldOsStatFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsStatFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsStatFuncCall is an object that describes an invocation of
// method OsStat on an instance of MockStubWorld.
type StubWorldOsStatFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 string
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 fs.FileInfo
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsStatFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsStatFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// MockStubWorldExecCmd is a mock implementation of the WorldExecCmd
// interface (from the package
// github.com/powerman/ebpf-same-cgroup-mark/internal) used for unit
// testing.
type MockStubWorldExecCmd struct {
	// CombinedOutputFunc is an instance of a mock function object
	// controlling the behavior of the method CombinedOutput.
	CombinedOutputFunc *StubWorldExecCmdCombinedOutputFunc
	// OutputFunc is an instance of a mock function object controlling the
	// behavior of the method Output.
	OutputFunc *StubWorldExecCmdOutputFunc
	// RunFunc is an instance of a mock function object controlling the
	// behavior of the method Run.
	RunFunc *StubWorldExecCmdRunFunc
}

// NewMockStubWorldExecCmd creates a new mock of the WorldExecCmd interface.
// All methods return zero values for all results, unless overwritten.
func NewMockStubWorldExecCmd() *MockStubWorldExecCmd {
	return &MockStubWorldExecCmd{
		CombinedOutputFunc: &StubWorldExecCmdCombinedOutputFunc{
			defaultHook: func() (r0 []byte, r1 error) {
				return
			},
		},
		OutputFunc: &StubWorldExecCmdOutputFunc{
			defaultHook: func() (r0 []byte, r1 error) {
				return
			},
		},
		RunFunc: &StubWorldExecCmdRunFunc{
			defaultHook: func() (r0 error) {
				return
			},
		},
	}
}

// NewStrictMockStubWorldExecCmd creates a new mock of the WorldExecCmd
// interface. All methods panic on invocation, unless overwritten.
func NewStrictMockStubWorldExecCmd() *MockStubWorldExecCmd {
	return &MockStubWorldExecCmd{
		CombinedOutputFunc: &StubWorldExecCmdCombinedOutputFunc{
			defaultHook: func() ([]byte, error) {
				panic("unexpected invocation of MockStubWorldExecCmd.CombinedOutput")
			},
		},
		OutputFunc: &StubWorldExecCmdOutputFunc{
			defaultHook: func() ([]byte, error) {
				panic("unexpected invocation of MockStubWorldExecCmd.Output")
			},
		},
		RunFunc: &StubWorldExecCmdRunFunc{
			defaultHook: func() error {
				panic("unexpected invocation of MockStubWorldExecCmd.Run")
			},
		},
	}
}

// NewMockStubWorldExecCmdFrom creates a new mock of the
// MockStubWorldExecCmd interface. All methods delegate to the given
// implementation, unless overwritten.
func NewMockStubWorldExecCmdFrom(i internal.WorldExecCmd) *MockStubWorldExecCmd {
	return &MockStubWorldExecCmd{
		CombinedOutputFunc: &StubWorldExecCmdCombinedOutputFunc{
			defaultHook: i.CombinedOutput,
		},
		OutputFunc: &StubWorldExecCmdOutputFunc{
			defaultHook: i.Output,
		},
		RunFunc: &StubWorldExecCmdRunFunc{
			defaultHook: i.Run,
		},
	}
}

// StubWorldExecCmdCombinedOutputFunc describes the behavior when the
// CombinedOutput method of the parent MockStubWorldExecCmd instance is
// invoked.
type StubWorldExecCmdCombinedOutputFunc struct {
	defaultHook func() ([]byte, error)
	hooks       []func() ([]byte, error)
	history     []StubWorldExecCmdCombinedOutputFuncCall
	mutex       sync.Mutex
}

// CombinedOutput delegates to the next hook function in the queue and
// stores the parameter and result values of this invocation.
func (m *MockStubWorldExecCmd) CombinedOutput() ([]byte, error) {
	r0, r1 := m.CombinedOutputFunc.nextHook()()
	m.CombinedOutputFunc.appendCall(StubWorldExecCmdCombinedOutputFuncCall{r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the CombinedOutput
// method of the parent MockStubWorldExecCmd instance is invoked and the
// hook queue is empty.
func (f *StubWorldExecCmdCombinedOutputFunc) SetDefaultHook(hook func() ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// CombinedOutput method of the parent MockStubWorldExecCmd instance invokes
// the hook at the front of the queue and discards it. After the queue is
// empty, the default hook function is invoked for any future action.
func (f *StubWorldExecCmdCombinedOutputFunc) PushHook(hook func() ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldExecCmdCombinedOutputFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func() ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldExecCmdCombinedOutputFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func() ([]byte, error) {
		return r0, r1
	})
}

func (f *StubWorldExecCmdCombinedOutputFunc) nextHook() func() ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldExecCmdCombinedOutputFunc) appendCall(r0 StubWorldExecCmdCombinedOutputFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldExecCmdCombinedOutputFuncCall
// objects describing the invocations of this function.
func (f *StubWorldExecCmdCombinedOutputFunc) History() []StubWorldExecCmdCombinedOutputFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldExecCmdCombinedOutputFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldExecCmdCombinedOutputFuncCall is an object that describes an
// invocation of method CombinedOutput on an instance of
// MockStubWorldExecCmd.
type StubWorldExecCmdCombinedOutputFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldExecCmdCombinedOutputFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldExecCmdCombinedOutputFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldExecCmdOutputFunc describes the behavior when the Output method
// of the parent MockStubWorldExecCmd instance is invoked.
type StubWorldExecCmdOutputFunc struct {
	defaultHook func() ([]byte, error)
	hooks       []func() ([]byte, error)
	history     []StubWorldExecCmdOutputFuncCall
	mutex       sync.Mutex
}

// Output delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldExecCmd) Output() ([]byte, error) {
	r0, r1 := m.OutputFunc.nextHook()()
	m.OutputFunc.appendCall(StubWorldExecCmdOutputFuncCall{r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the Output method of the
// parent MockStubWorldExecCmd instance is invoked and the hook queue is
// empty.
func (f *StubWorldExecCmdOutputFunc) SetDefaultHook(hook func() ([]byte, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Output method of the parent MockStubWorldExecCmd instance invokes the
// hook at the front of the queue and discards it. After the queue is empty,
// the default hook function is invoked for any future action.
func (f *StubWorldExecCmdOutputFunc) PushHook(hook func() ([]byte, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldExecCmdOutputFunc) SetDefaultReturn(r0 []byte, r1 error) {
	f.SetDefaultHook(func() ([]byte, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldExecCmdOutputFunc) PushReturn(r0 []byte, r1 error) {
	f.PushHook(func() ([]byte, error) {
		return r0, r1
	})
}

func (f *StubWorldExecCmdOutputFunc) nextHook() func() ([]byte, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldExecCmdOutputFunc) appendCall(r0 StubWorldExecCmdOutputFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldExecCmdOutputFuncCall objects
// describing the invocations of this function.
func (f *StubWorldExecCmdOutputFunc) History() []StubWorldExecCmdOutputFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldExecCmdOutputFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldExecCmdOutputFuncCall is an object that describes an invocation
// of method Output on an instance of MockStubWorldExecCmd.
type StubWorldExecCmdOutputFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 []byte
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldExecCmdOutputFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldExecCmdOutputFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}

// StubWorldExecCmdRunFunc describes the behavior when the Run method of the
// parent MockStubWorldExecCmd instance is invoked.
type StubWorldExecCmdRunFunc struct {
	defaultHook func() error
	hooks       []func() error
	history     []StubWorldExecCmdRunFuncCall
	mutex       sync.Mutex
}

// Run delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldExecCmd) Run() error {
	r0 := m.RunFunc.nextHook()()
	m.RunFunc.appendCall(StubWorldExecCmdRunFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Run method of the
// parent MockStubWorldExecCmd instance is invoked and the hook queue is
// empty.
func (f *StubWorldExecCmdRunFunc) SetDefaultHook(hook func() error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Run method of the parent MockStubWorldExecCmd instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldExecCmdRunFunc) PushHook(hook func() error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldExecCmdRunFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func() error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldExecCmdRunFunc) PushReturn(r0 error) {
	f.PushHook(func() error {
		return r0
	})
}

func (f *StubWorldExecCmdRunFunc) nextHook() func() error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldExecCmdRunFunc) appendCall(r0 StubWorldExecCmdRunFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldExecCmdRunFuncCall objects
// describing the invocations of this function.
func (f *StubWorldExecCmdRunFunc) History() []StubWorldExecCmdRunFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldExecCmdRunFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldExecCmdRunFuncCall is an object that describes an invocation of
// method Run on an instance of MockStubWorldExecCmd.
type StubWorldExecCmdRunFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldExecCmdRunFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldExecCmdRunFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// MockStubWorldOsFile is a mock implementation of the WorldOsFile interface
// (from the package github.com/powerman/ebpf-same-cgroup-mark/internal)
// used for unit testing.
type MockStubWorldOsFile struct {
	// CloseFunc is an instance of a mock function object controlling the
	// behavior of the method Close.
	CloseFunc *StubWorldOsFileCloseFunc
	// NameFunc is an instance of a mock function object controlling the
	// behavior of the method Name.
	NameFunc *StubWorldOsFileNameFunc
	// WriteFunc is an instance of a mock function object controlling the
	// behavior of the method Write.
	WriteFunc *StubWorldOsFileWriteFunc
}

// NewMockStubWorldOsFile creates a new mock of the WorldOsFile interface.
// All methods return zero values for all results, unless overwritten.
func NewMockStubWorldOsFile() *MockStubWorldOsFile {
	return &MockStubWorldOsFile{
		CloseFunc: &StubWorldOsFileCloseFunc{
			defaultHook: func() (r0 error) {
				return
			},
		},
		NameFunc: &StubWorldOsFileNameFunc{
			defaultHook: func() (r0 string) {
				return
			},
		},
		WriteFunc: &StubWorldOsFileWriteFunc{
			defaultHook: func([]byte) (r0 int, r1 error) {
				return
			},
		},
	}
}

// NewStrictMockStubWorldOsFile creates a new mock of the WorldOsFile
// interface. All methods panic on invocation, unless overwritten.
func NewStrictMockStubWorldOsFile() *MockStubWorldOsFile {
	return &MockStubWorldOsFile{
		CloseFunc: &StubWorldOsFileCloseFunc{
			defaultHook: func() error {
				panic("unexpected invocation of MockStubWorldOsFile.Close")
			},
		},
		NameFunc: &StubWorldOsFileNameFunc{
			defaultHook: func() string {
				panic("unexpected invocation of MockStubWorldOsFile.Name")
			},
		},
		WriteFunc: &StubWorldOsFileWriteFunc{
			defaultHook: func([]byte) (int, error) {
				panic("unexpected invocation of MockStubWorldOsFile.Write")
			},
		},
	}
}

// NewMockStubWorldOsFileFrom creates a new mock of the MockStubWorldOsFile
// interface. All methods delegate to the given implementation, unless
// overwritten.
func NewMockStubWorldOsFileFrom(i internal.WorldOsFile) *MockStubWorldOsFile {
	return &MockStubWorldOsFile{
		CloseFunc: &StubWorldOsFileCloseFunc{
			defaultHook: i.Close,
		},
		NameFunc: &StubWorldOsFileNameFunc{
			defaultHook: i.Name,
		},
		WriteFunc: &StubWorldOsFileWriteFunc{
			defaultHook: i.Write,
		},
	}
}

// StubWorldOsFileCloseFunc describes the behavior when the Close method of
// the parent MockStubWorldOsFile instance is invoked.
type StubWorldOsFileCloseFunc struct {
	defaultHook func() error
	hooks       []func() error
	history     []StubWorldOsFileCloseFuncCall
	mutex       sync.Mutex
}

// Close delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldOsFile) Close() error {
	r0 := m.CloseFunc.nextHook()()
	m.CloseFunc.appendCall(StubWorldOsFileCloseFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Close method of the
// parent MockStubWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsFileCloseFunc) SetDefaultHook(hook func() error) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Close method of the parent MockStubWorldOsFile instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsFileCloseFunc) PushHook(hook func() error) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsFileCloseFunc) SetDefaultReturn(r0 error) {
	f.SetDefaultHook(func() error {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsFileCloseFunc) PushReturn(r0 error) {
	f.PushHook(func() error {
		return r0
	})
}

func (f *StubWorldOsFileCloseFunc) nextHook() func() error {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsFileCloseFunc) appendCall(r0 StubWorldOsFileCloseFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsFileCloseFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsFileCloseFunc) History() []StubWorldOsFileCloseFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsFileCloseFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsFileCloseFuncCall is an object that describes an invocation of
// method Close on an instance of MockStubWorldOsFile.
type StubWorldOsFileCloseFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsFileCloseFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsFileCloseFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsFileNameFunc describes the behavior when the Name method of
// the parent MockStubWorldOsFile instance is invoked.
type StubWorldOsFileNameFunc struct {
	defaultHook func() string
	hooks       []func() string
	history     []StubWorldOsFileNameFuncCall
	mutex       sync.Mutex
}

// Name delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldOsFile) Name() string {
	r0 := m.NameFunc.nextHook()()
	m.NameFunc.appendCall(StubWorldOsFileNameFuncCall{r0})
	return r0
}

// SetDefaultHook sets function that is called when the Name method of the
// parent MockStubWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsFileNameFunc) SetDefaultHook(hook func() string) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Name method of the parent MockStubWorldOsFile instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsFileNameFunc) PushHook(hook func() string) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsFileNameFunc) SetDefaultReturn(r0 string) {
	f.SetDefaultHook(func() string {
		return r0
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsFileNameFunc) PushReturn(r0 string) {
	f.PushHook(func() string {
		return r0
	})
}

func (f *StubWorldOsFileNameFunc) nextHook() func() string {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsFileNameFunc) appendCall(r0 StubWorldOsFileNameFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsFileNameFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsFileNameFunc) History() []StubWorldOsFileNameFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsFileNameFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsFileNameFuncCall is an object that describes an invocation of
// method Name on an instance of MockStubWorldOsFile.
type StubWorldOsFileNameFuncCall struct {
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 string
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsFileNameFuncCall) Args() []interface{} {
	return []interface{}{}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsFileNameFuncCall) Results() []interface{} {
	return []interface{}{c.Result0}
}

// StubWorldOsFileWriteFunc describes the behavior when the Write method of
// the parent MockStubWorldOsFile instance is invoked.
type StubWorldOsFileWriteFunc struct {
	defaultHook func([]byte) (int, error)
	hooks       []func([]byte) (int, error)
	history     []StubWorldOsFileWriteFuncCall
	mutex       sync.Mutex
}

// Write delegates to the next hook function in the queue and stores the
// parameter and result values of this invocation.
func (m *MockStubWorldOsFile) Write(v0 []byte) (int, error) {
	r0, r1 := m.WriteFunc.nextHook()(v0)
	m.WriteFunc.appendCall(StubWorldOsFileWriteFuncCall{v0, r0, r1})
	return r0, r1
}

// SetDefaultHook sets function that is called when the Write method of the
// parent MockStubWorldOsFile instance is invoked and the hook queue is
// empty.
func (f *StubWorldOsFileWriteFunc) SetDefaultHook(hook func([]byte) (int, error)) {
	f.defaultHook = hook
}

// PushHook adds a function to the end of hook queue. Each invocation of the
// Write method of the parent MockStubWorldOsFile instance invokes the hook
// at the front of the queue and discards it. After the queue is empty, the
// default hook function is invoked for any future action.
func (f *StubWorldOsFileWriteFunc) PushHook(hook func([]byte) (int, error)) {
	f.mutex.Lock()
	f.hooks = append(f.hooks, hook)
	f.mutex.Unlock()
}

// SetDefaultReturn calls SetDefaultHook with a function that returns the
// given values.
func (f *StubWorldOsFileWriteFunc) SetDefaultReturn(r0 int, r1 error) {
	f.SetDefaultHook(func([]byte) (int, error) {
		return r0, r1
	})
}

// PushReturn calls PushHook with a function that returns the given values.
func (f *StubWorldOsFileWriteFunc) PushReturn(r0 int, r1 error) {
	f.PushHook(func([]byte) (int, error) {
		return r0, r1
	})
}

func (f *StubWorldOsFileWriteFunc) nextHook() func([]byte) (int, error) {
	f.mutex.Lock()
	defer f.mutex.Unlock()

	if len(f.hooks) == 0 {
		return f.defaultHook
	}

	hook := f.hooks[0]
	f.hooks = f.hooks[1:]
	return hook
}

func (f *StubWorldOsFileWriteFunc) appendCall(r0 StubWorldOsFileWriteFuncCall) {
	f.mutex.Lock()
	f.history = append(f.history, r0)
	f.mutex.Unlock()
}

// History returns a sequence of StubWorldOsFileWriteFuncCall objects
// describing the invocations of this function.
func (f *StubWorldOsFileWriteFunc) History() []StubWorldOsFileWriteFuncCall {
	f.mutex.Lock()
	history := make([]StubWorldOsFileWriteFuncCall, len(f.history))
	copy(history, f.history)
	f.mutex.Unlock()

	return history
}

// StubWorldOsFileWriteFuncCall is an object that describes an invocation of
// method Write on an instance of MockStubWorldOsFile.
type StubWorldOsFileWriteFuncCall struct {
	// Arg0 is the value of the 1st argument passed to this method
	// invocation.
	Arg0 []byte
	// Result0 is the value of the 1st result returned from this method
	// invocation.
	Result0 int
	// Result1 is the value of the 2nd result returned from this method
	// invocation.
	Result1 error
}

// Args returns an interface slice containing the arguments of this
// invocation.
func (c StubWorldOsFileWriteFuncCall) Args() []interface{} {
	return []interface{}{c.Arg0}
}

// Results returns an interface slice containing the results of this
// invocation.
func (c StubWorldOsFileWriteFuncCall) Results() []interface{} {
	return []interface{}{c.Result0, c.Result1}
}
