name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel testing of a previous commit for the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # To update gh-badges branch.

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            clang llvm libbpf-dev

      - uses: jdx/mise-action@v4
      - run: git reset --hard # Work around https://github.com/jdx/mise/discussions/8270.

      - uses: powerman/.github/.github/actions/cache-go-and-tools@main

      - run: mise run ci

      - uses: powerman/.github/.github/actions/coverage-badge@main
        if: github.ref_name == 'main'
        with:
          total_cmd: "mise run -q cover:go:total | tail -n 1 | sed -e 's/.*)//'"

      - name: Install integration test dependencies
        run: sudo apt-get install -y --no-install-recommends nftables socat

      - name: Build
        run: mise run build

      - name: Clear kernel ring buffer
        if: always()
        run: sudo dmesg --clear

      - name: Integration test
        run: timeout 30 sudo -E "$(which mise)" exec -- bash .github/integration_test.sh

      - name: Show relevant kernel messages
        if: always()
        run: sudo dmesg

  # Testing on available native platforms.
  native:
    strategy:
      matrix:
        include:
          - {os: ubuntu-24.04-arm} # Linux ARM64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            clang llvm libbpf-dev

      - uses: jdx/mise-action@v4
      - run: git reset --hard # Work around https://github.com/jdx/mise/discussions/8270.

      - run: mise run test

      - name: Install integration test dependencies
        run: sudo apt-get install -y --no-install-recommends nftables socat

      - name: Build
        run: mise run build

      - name: Clear kernel ring buffer
        if: always()
        run: sudo dmesg --clear

      - name: Integration test
        run: timeout 30 sudo -E "$(which mise)" exec -- bash .github/integration_test.sh

      - name: Show relevant kernel messages
        if: always()
        run: sudo dmesg | grep -aiE 'mark|same_cgroup' | tail -20 || true

  # Aggregate job for branch protection.
  test:
    needs: [main, native]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Fail if any dependency failed, cancelled or skipped
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped')
        run: exit 1
